const app=document.getElementById("app"),params=new URLSearchParams(location.search),id=params.get("id"),key=id?`draftReport:${id}`:"";
const esc=value=>String(value??"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]));
const pct=value=>`${(Number(value||0)*100).toFixed(3)}%`;
const pp=value=>`${Number(value||0)>=0?"+":""}${(Number(value||0)*100).toFixed(2)} pp`;
const renderReport=report=>{
  if(!report){app.innerHTML='<section class="card">This saved report is unavailable.</section>';return}
  const user=report.userTeam,standings=[...report.teamReports].sort((a,b)=>a.titleRank-b.titleRank),fair=1/Number(report.teams||1),leader=Math.max(...standings.map(team=>Number(team.finishProbabilities?.[0]||0)));
  app.innerHTML=`<h1>Draft Goblin report</h1><div class="top"><section class="card grade"><span class="muted">Overall draft grade</span><strong>${esc(report.grade.letter)}</strong><h2>${Number(report.grade.score)} / 100</h2><span class="muted">Title odds only; rank alone is not a grade.</span></section><section class="card"><span class="muted">Championship outlook</span><h2>${pct(user.finishProbabilities[0])} title chance</h2><p>Title-odds rank <strong>#${user.titleRank}</strong> of ${report.teams} | projected weekly rank <strong>#${user.weeklyRank}</strong></p><p class="muted">${Number(user.pointsExact??user.points).toFixed(3)} projected points/week</p></section></div><section class="card"><h2>How to read this result</h2><div class="finish"><div><strong>#${user.weeklyRank} of ${report.teams}</strong><span>Projected weekly scoring</span></div><div><strong>#${user.titleRank} of ${report.teams}</strong><span>Point-estimate title rank</span></div><div><strong>${pp(Number(user.finishProbabilities[0])-fair)}</strong><span>Versus equal-team odds</span></div><div><strong>${pp(Number(user.finishProbabilities[0])-leader)}</strong><span>Gap to the leader</span></div></div><p class="muted">Small simulated title-odds differences can move a team several rank positions. Judge the probability gaps, not the ordinal rank by itself.</p></section><section class="card"><h2>Your draft</h2><table><thead><tr><th>Round</th><th>Pick</th><th>Player</th><th>Position</th><th>Team</th></tr></thead><tbody>${user.draft.map(p=>`<tr><td>${p.round}</td><td>#${p.pickNo}</td><td><strong>${esc(p.name)}</strong></td><td>${esc(p.position)}</td><td>${esc(p.team)}</td></tr>`).join("")}</tbody></table></section><section class="card"><h2>Championship odds ranking</h2><table><thead><tr><th>Rank</th><th>Team</th><th>Title chance</th><th>Projected points/week</th></tr></thead><tbody>${standings.map(team=>`<tr><td>#${team.titleRank}</td><td>${team.slot===report.userSlot?"<strong>Your team</strong>":`Team ${team.slot}`}</td><td>${pct(team.finishProbabilities[0])}</td><td>${Number(team.pointsExact??team.points).toFixed(3)}</td></tr>`).join("")}</tbody></table><p class="muted">${Number(report.iterations).toLocaleString()} simulations. ${esc(report.method)}</p></section>`;
};
const renderReportWithoutLosingPlace=report=>{const left=scrollX,top=scrollY;renderReport(report);requestAnimationFrame(()=>scrollTo(left,top))};
if(!key)app.innerHTML='<section class="card">This report link is invalid.</section>';else{
  chrome.storage.onChanged.addListener((changes,area)=>{if(area==="local"&&changes[key]?.newValue)renderReportWithoutLosingPlace(changes[key].newValue)});
  chrome.storage.local.get(key).then(stored=>renderReport(stored[key])).catch(error=>{app.innerHTML=`<section class="card">${esc(error.message||error)}</section>`});
}
