import test from "node:test";
import assert from "node:assert/strict";
import { compareRecommendationSets, DistributionShadowTelemetry, scheduleDistributionShadow, shadowStates } from "../server/distribution-shadow.js";
const item = (id, chance) => ({ player: { id }, simulation: { championshipProbability: chance } });
test("shadow comparison reports disagreement without changing live ordering", () => { const result = compareRecommendationSets([item("a", .2), item("b", .1)], [item("b", .21), item("a", .11)]); assert.equal(result.topPickDisagreed, true); assert.equal(result.liveOrderingChanged, false); assert.equal(result.maximumAbsoluteRankDelta, 1); });
test("shadow states are isolated and strip distributions from legacy", () => { const distribution = { schemaVersion: "quantile-v1" }, original = { players: [{ id: "a", distribution: { old: true }, shadowDistribution: distribution }] }, states = shadowStates(original); assert.equal(states.legacy.players[0].distribution, undefined); assert.deepEqual(states.quantile.players[0].distribution, distribution); states.quantile.players[0].id = "changed"; assert.equal(original.players[0].id, "a"); });
test("telemetry is bounded", () => { const telemetry = new DistributionShadowTelemetry(2); telemetry.record({ topPickDisagreed: false }); telemetry.record({ topPickDisagreed: true }); telemetry.record({ topPickDisagreed: true }); const diagnostics = telemetry.diagnostics(); assert.equal(diagnostics.entries, 2); assert.equal(diagnostics.topPickDisagreements, 2); });
test("default-off shadow performs no evaluation and records no telemetry", async () => { const telemetry = new DistributionShadowTelemetry(), state = { projectionSeason: 2026, players: [{ id: "a", mean: 100, floor: 70, ceiling: 140 }] }; let calls = 0; assert.equal(scheduleDistributionShadow({ state, telemetry, enabled: false, evaluate() { calls++; return []; } }), false); await new Promise(resolve => setImmediate(resolve)); assert.equal(calls, 0); assert.equal(telemetry.diagnostics().entries, 0); });
test("explicitly enabled shadow creates quantiles and collects an isolated comparison", async () => { const telemetry = new DistributionShadowTelemetry(), state = { projectionSeason: 2026, players: [{ id: "a", mean: 100, floor: 70, ceiling: 140 }, { id: "b", mean: 95, floor: 75, ceiling: 150 }] }; const seen = []; assert.equal(scheduleDistributionShadow({ state, telemetry, enabled: true, evaluate({ state: evaluated }) { const quantile = Boolean(evaluated.players[0].distribution); seen.push(quantile); return quantile ? [item("b", .2), item("a", .1)] : [item("a", .2), item("b", .1)]; } }), true); await new Promise(resolve => setImmediate(resolve)); assert.deepEqual(seen, [false, true]); assert.equal(telemetry.diagnostics().entries, 1); assert.equal(telemetry.diagnostics().recent[0].topPickDisagreed, true); assert.equal(state.players[0].distribution, undefined); assert.equal(state.players[0].shadowDistribution, undefined); });
