import test from"node:test";
import assert from"node:assert/strict";
import fs from"node:fs";
import os from"node:os";
import path from"node:path";
import{currentFantasyPros,fantasyProsPoints,latestFantasyProsSnapshot,parseFantasyProsHtml}from"../server/fantasypros.js";

test("FantasyPros API parser selects the requested scoring format",()=>{const payload={players:[{fpid:1,name:"One",position_id:"RB",team_id:"SEA",stats:{points:100,points_half:125,points_ppr:150}}]};assert.equal(fantasyProsPoints(payload,"PPR")[0].points,150);assert.equal(fantasyProsPoints(payload,"HALF")[0].points,125);assert.equal(fantasyProsPoints(payload,"STD")[0].points,100)});
test("keyless FantasyPros HTML parser reads player identity and final fantasy points",()=>{const html='<table id="data"><tr><td class="player-label"><a class="fp-id-23133" fp-player-name="Bijan Robinson">Bijan Robinson</a> ATL</td><td class="center">289.5</td><td class="center" data-sort-value="369.843">369.8</td></tr></table>',player=parseFantasyProsHtml(html,"rb")[0];assert.deepEqual(player,{id:"23133",name:"Bijan Robinson",position:"RB",team:"ATL",points:369.843})});
test("keyless FantasyPros ingestion requests complete print tables for every position",async()=>{const urls=[];const result=await currentFantasyPros({season:2097,scoring:"PPR",captureSnapshot:false,fetchImpl:async url=>{urls.push(String(url));return{ok:true,text:async()=>'<table><tr><td><a class="fp-id-1" fp-player-name="Test Player">Test Player</a> BUF</td><td class="center" data-sort-value="100">100</td></tr></table>'}}});assert.equal(result.players.length,6);assert.equal(urls.length,6);assert.ok(urls.every(url=>new URL(url).searchParams.get("print")==="true"))});
test("keyless FantasyPros ingestion preserves healthy positions when one page fails",async()=>{const result=await currentFantasyPros({season:2096,scoring:"HALF",captureSnapshot:false,fetchImpl:async url=>String(url).includes("/wr.php")?{ok:false,status:503}:{ok:true,text:async()=>'<table><tr><td><a class="fp-id-1" fp-player-name="Test Player">Test Player</a> BUF</td><td class="center" data-sort-value="100">100</td></tr></table>'}});assert.equal(result.available,true);assert.equal(result.partial,true);assert.deepEqual(result.failedPositions,["WR"]);assert.equal(result.players.length,5)});
test("FantasyPros official connector sends the key server-side",async()=>{let request;const fetchImpl=async(url,options)=>{request={url:String(url),options};return{ok:true,json:async()=>({players:[{fpid:7,name:"Seven",position_id:"WR",team_id:"X",stats:{points_ppr:177.7}}]})}};const result=await currentFantasyPros({season:2099,scoring:"PPR",apiKey:"secret",fetchImpl,captureSnapshot:false});assert.equal(result.players[0].points,177.7);assert.match(request.url,/2099\/projections/);assert.equal(request.options.headers["x-api-key"],"secret")});
test("FantasyPros connector uses public projection tables when no key is configured",async()=>{const html='<tr><td><a class="fp-id-9" fp-player-name="Public Player">Public Player</a> SEA</td><td class="center" data-sort-value="123.4">123.4</td></tr>',fetchImpl=async()=>({ok:true,text:async()=>html}),result=await currentFantasyPros({season:2098,scoring:"PPR",apiKey:"",fetchImpl,captureSnapshot:false});assert.equal(result.available,true);assert.equal(result.access,"public-html");assert.equal(result.players.length,6);assert.equal(result.players[0].points,123.4);assert.ok(result.fetchedAt)});
test("successful ten-row pages recover only the truncated position from a recent complete snapshot",async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"draft-champion-fp-")),now=Date.parse("2094-07-13T18:00:00Z"),row=(id,name,points)=>`<tr><td><a class="fp-id-${id}" fp-player-name="${name}">${name}</a> BUF</td><td class="center" data-sort-value="${points}">${points}</td></tr>`,rows=(prefix,count,firstPoints=100)=>Array.from({length:count},(_,index)=>row(index+1,`${prefix} Player ${index}`,index?100+index:firstPoints)).join("");fs.writeFileSync(path.join(directory,"fantasypros-2094-PPR-complete.json"),JSON.stringify({season:2094,scoring:"PPR",fetchedAt:"2094-07-13T17:00:00Z",players:Array.from({length:12},(_,index)=>({id:String(index+1),name:`rb Player ${index}`,position:"RB",team:"BUF",points:100+index}))}));const result=await currentFantasyPros({season:2094,scoring:"PPR",apiKey:"",snapshotDirectory:new URL(`file:///${directory.replaceAll("\\","/")}/`),now,captureSnapshot:true,fetchImpl:async url=>{const position=String(url).match(/\/([^/]+)\.php/)?.[1];return{ok:true,text:async()=>rows(position,position==="rb"?10:11,999)}}});assert.deepEqual(result.truncatedPositions,["RB"]);assert.deepEqual(result.recoveredPositions,["RB"]);assert.equal(result.players.filter(player=>player.position==="RB").length,12);assert.equal(result.players.find(player=>player.name==="rb Player 0").points,999);const captured=JSON.parse(fs.readFileSync(path.join(directory,"fantasypros-2094-PPR-2094-07-13T18-00-00-000Z.json"),"utf8"));assert.equal(captured.players.filter(player=>player.position==="RB").length,10)});
test("FantasyPros snapshot fallback merges fresh matching snapshots with newest player records winning",()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"draft-champion-fp-")),now=Date.parse("2026-07-13T18:00:00Z"),write=(name,value)=>fs.writeFileSync(path.join(directory,name),JSON.stringify(value));write("fantasypros-old.json",{season:2026,scoring:"PPR",fetchedAt:"2026-07-12T18:00:00Z",players:[{id:"shared",name:"Shared",points:100},{id:"old-only",name:"Old",points:90}]});write("fantasypros-new.json",{season:2026,scoring:"PPR",fetchedAt:"2026-07-13T17:00:00Z",players:[{id:"shared",name:"Shared",points:200},{id:"new-only",name:"New",points:180}]});write("fantasypros-wrong.json",{season:2026,scoring:"STD",fetchedAt:"2026-07-13T17:30:00Z",players:[{name:"Wrong",points:300}]});const result=latestFantasyProsSnapshot({season:2026,scoring:"PPR",directory:new URL(`file:///${directory.replaceAll("\\","/")}/`),now});assert.equal(result.players.find(player=>player.id==="shared").points,200);assert.deepEqual(result.players.map(player=>player.id),["shared","new-only","old-only"]);assert.equal(result.access,"local-snapshot-fallback");assert.equal(result.snapshotAgeMs,60*60*1000);assert.equal(result.snapshotCount,2)});
test("healthy-looking live pages recover individually omitted players from recent snapshots",async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"draft-champion-fp-")),now=Date.parse("2093-07-13T18:00:00Z"),row=(id,name,position,points)=>`<tr><td><a class="fp-id-${id}" fp-player-name="${name}">${name}</a> MIN</td><td class="center" data-sort-value="${points}">${points}</td></tr>`;fs.writeFileSync(path.join(directory,"fantasypros-2093-PPR-prior.json"),JSON.stringify({season:2093,scoring:"PPR",fetchedAt:"2093-07-13T17:00:00Z",players:[{id:"8408",name:"Jordan Mason",position:"RB",team:"MIN",points:135.565}]}));const result=await currentFantasyPros({season:2093,scoring:"PPR",apiKey:"",snapshotDirectory:new URL(`file:///${directory.replaceAll("\\","/")}/`),now,captureSnapshot:false,fetchImpl:async url=>{const position=String(url).match(/\/([^/]+)\.php/)?.[1].toUpperCase();return{ok:true,text:async()=>Array.from({length:11},(_,index)=>row(`${position}${index}`,`${position} Player ${index}`,position,100+index)).join("")}}});assert.equal(result.partial,false);assert.equal(result.players.find(player=>player.name==="Jordan Mason").points,135.565);assert.equal(result.snapshotRecoveredPlayerCount,1)});
test("snapshot merging deduplicates a player when FantasyPros changes its numeric id",()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"draft-champion-fp-")),now=Date.parse("2092-07-13T18:00:00Z"),write=(name,value)=>fs.writeFileSync(path.join(directory,name),JSON.stringify(value));write("fantasypros-new.json",{season:2092,scoring:"PPR",fetchedAt:"2092-07-13T17:00:00Z",players:[{id:"8408",name:"Jordan Mason",position:"RB",points:140}]});write("fantasypros-old.json",{season:2092,scoring:"PPR",fetchedAt:"2092-07-12T17:00:00Z",players:[{id:"22969",name:"Jordan Mason",position:"RB",points:135}]});const result=latestFantasyProsSnapshot({season:2092,scoring:"PPR",directory:new URL(`file:///${directory.replaceAll("\\","/")}/`),now});assert.equal(result.players.filter(player=>player.name==="Jordan Mason").length,1);assert.equal(result.players[0].points,140)});
test("FantasyPros live failure returns a recent same-format local snapshot with explicit metadata",async()=>{const directory=fs.mkdtempSync(path.join(os.tmpdir(),"draft-champion-fp-")),now=Date.parse("2095-07-13T18:00:00Z"),snapshot={season:2095,scoring:"HALF",fetchedAt:"2095-07-13T17:00:00Z",source:"FantasyPros public consensus",players:[{id:"1",name:"Snapshot Player",position:"RB",team:"BUF",points:123}]};fs.writeFileSync(path.join(directory,"fantasypros-2095-HALF-snapshot.json"),JSON.stringify(snapshot));const result=await currentFantasyPros({season:2095,scoring:"HALF",apiKey:"",captureSnapshot:false,snapshotDirectory:new URL(`file:///${directory.replaceAll("\\","/")}/`),now,fetchImpl:async()=>{throw new Error("fetch failed")}});assert.equal(result.players[0].name,"Snapshot Player");assert.equal(result.fallback,true);assert.equal(result.access,"local-snapshot-fallback");assert.equal(result.liveFetchError,"fetch failed")});
