import test from"node:test";import assert from"node:assert/strict";import fs from"node:fs";
const workflow=fs.readFileSync(new URL("../.github/workflows/owned-model-shadow.yml",import.meta.url),"utf8");
const publisher=fs.readFileSync(new URL("../.github/workflows/publish-projections.yml",import.meta.url),"utf8");
const fetcher=fs.readFileSync(new URL("../scripts/fetch-owned-model-data.py",import.meta.url),"utf8");
const predictor=fs.readFileSync(new URL("../scripts/predict-owned-model.py",import.meta.url),"utf8");
const verifier=fs.readFileSync(new URL("../scripts/verify-owned-shadow-artifacts.py",import.meta.url),"utf8");
const gitignore=fs.readFileSync(new URL("../.gitignore",import.meta.url),"utf8");
test("owned workflow builds only a verified retained shadow artifact",()=>{
  assert.match(workflow,/python -m compileall -q owned_model scripts/);
  assert.match(workflow,/cache-dependency-path: requirements-owned-model\.txt/);
  assert.match(workflow,/python -m unittest discover -s owned_model -p "test_\*\.py"/);
  assert.match(workflow,/node --test test\/owned-model-\*\.test\.js/);
  assert.match(workflow,/verify-owned-shadow-artifacts\.py/);
  assert.match(workflow,/uses: actions\/attest@v4/);
  assert.match(workflow,/id-token: write/);
  assert.match(workflow,/attestations: write/);
  assert.match(predictor,/load_model\(Path\(args\.model\)\)/);
  assert.match(predictor,/predict_owned_model\(/);
  assert.match(verifier,/runtimeStatus"\) == "shadow"/);
  assert.match(verifier,/eligibleAsLiveProjection"\) is False/);
  assert.match(verifier,/report\.get\("modelVersion"\) == MODEL_VERSION/);
  assert.match(verifier,/policy_model\.get\("status"\) == "shadow"/);
  assert.match(workflow,/upload-artifact@v4/);
  for(const retained of["model.joblib","owned-projections-","owned-model-walk-forward.json","fetch-manifest.json","shadow-build-manifest.json"])assert.match(workflow,new RegExp(retained.replace(".","\\.")));
  assert.match(workflow,/if-no-files-found: error/);
  assert.match(workflow,/retention-days: 90/);
  assert.doesNotMatch(workflow,/git\s+(push|commit)/i);
  assert.doesNotMatch(workflow,/deploy-pages|upload-pages-artifact/);
  assert.doesNotMatch(workflow,/prospective-\d{4}|owned-prospective-freeze/i);
  assert.match(gitignore,/^data\/private\/$/m);
});
test("live projection publication builds and publishes the fresh market-adjusted shadow",()=>{
  assert.match(publisher,/fetch-owned-model-data\.py/);
  assert.match(publisher,/train-owned-model\.py/);
  assert.match(publisher,/build-owned-market-shadow\.js/);
  assert.match(publisher,/publish-projection-feed\.js --owned-only/);
  assert.match(publisher,/owned-market-shadow-\$\{PROJECTION_SEASON/);
  assert.doesNotMatch(publisher,/download-artifact|owned-model-shadow\.yml|data\/generated\/owned-projections/i);
});
test("owned data fetch includes the preseason draft-capital input",()=>{assert.match(fetcher,/releases\/download\/draft_picks\/draft_picks\.csv/);assert.match(fetcher,/output \/ "draft_picks\.csv"/)});
