import test from"node:test";
import assert from"node:assert/strict";
import fs from"node:fs";
import os from"node:os";
import path from"node:path";
import{buildDraftGoblinFeeds,buildProjectionPublication,buildWeightedConsensusFeeds,publishableFeeds,writeProjectionPublication}from"../scripts/publish-projection-feed.js";
import{sha256Hex}from"../extension/projection-feed.js";

const NOW=Date.parse("2026-07-15T12:00:00.000Z"),positions=["QB","RB","WR","TE"],players=Array.from({length:160},(_,index)=>({id:`p${index}`,name:`Player ${index}`,position:positions[index%positions.length],team:"BUF",points:100+index,season:2026,scoring:"PPR"})),providerFormats=(sourceDelta,fetchedAt)=>Object.fromEntries(["STD","HALF","PPR"].map(scoring=>[scoring,{season:2026,scoring,fetchedAt,players:players.map(player=>({...player,id:`${sourceDelta}:${player.id}`,points:player.points+sourceDelta,scoring}))}])),collected={feeds:{sleeper:providerFormats(0,"2026-07-15T10:00:00.000Z"),fantasyPros:providerFormats(20,"2026-07-15T10:05:00.000Z")},provenance:{sleeper:{policySourceId:"sleeper-source"},fantasyPros:{policySourceId:"fantasypros-source"}}},owned={artifactType:"draft-goblin-owned-market-shadow-candidate",projectionVariant:"market-adjusted-shadow-v2",projectionSeason:2026,generatedAt:"2026-07-15T10:30:00.000Z",runtimeStatus:"shadow",eligibleAsLiveProjection:false,modelVersion:"owned-test-pure-market-shadow-v2",players:players.map(player=>({...player,meanStd:player.points-20,meanHalf:player.points-10,meanPpr:player.points}))},policy=status=>({sources:[{id:"sleeper-source",status,license:status==="allowed-for-redistribution"?"written":"not established"},{id:"fantasypros-source",status,license:status==="allowed-for-redistribution"?"commercial":"not established"}]});
test("publisher fails closed unless source policy explicitly allows redistribution",()=>{assert.deepEqual(publishableFeeds(collected,policy("pending-redistribution-rights")),{});assert.throws(()=>buildProjectionPublication({collected,policy:policy("pending-redistribution-rights"),draftGoblinArtifact:owned,now:NOW}),/No current projection source/)});
test("publisher requires the market-adjusted shadow artifact",()=>{const withAvailability={...owned,players:owned.players.map((player,index)=>index?player:{...player,expectedGames:14.48,activeRoleGames:17})},feed=buildDraftGoblinFeeds(withAvailability).draftGoblin;assert.deepEqual(Object.keys(feed),["STD","HALF","PPR"]);assert.equal(feed.PPR.projectionVariant,"market-adjusted-shadow-v2");assert.equal(feed.PPR.players[0].expectedGames,14.48);assert.equal(feed.PPR.players[0].activeRoleGames,17);assert.equal(feed.PPR.players[0].availabilityModelVersion,"owned-test-pure-market-shadow-v2");assert.throws(()=>buildDraftGoblinFeeds({...owned,artifactType:"draft-goblin-owned-projections"}),/market-adjusted shadow/)});
test("provider-free publication contains only the Draft Goblin feed",()=>{const publication=buildProjectionPublication({draftGoblinArtifact:owned,aggregateMode:"owned",now:NOW}),published=JSON.parse(publication.bytes);assert.deepEqual(Object.keys(published.feeds),["draftGoblin"]);assert.equal(JSON.stringify(published).includes("conservative owned ensemble"),false);assert.equal(JSON.stringify(published).includes("FantasyPros"),false);assert.equal(JSON.stringify(published).includes("Sleeper"),false)});
test("provider-free publication deterministically resolves duplicate owned player identities",()=>{const duplicate={...owned.players[0],name:"Duplicate Player",meanStd:501,meanHalf:502,meanPpr:503},artifact={...owned,players:[...owned.players,duplicate]},publication=buildProjectionPublication({draftGoblinArtifact:artifact,aggregateMode:"owned",now:NOW}),published=JSON.parse(publication.bytes);for(const scoring of["STD","HALF","PPR"]){const matches=published.feeds.draftGoblin[scoring].players.filter(player=>player.id==="p0"&&player.position===owned.players[0].position);assert.equal(matches.length,1)}assert.equal(published.feeds.draftGoblin.PPR.players.find(player=>player.id==="p0").points,503)});
test("publisher emits only Draft Goblin and weighted consensus rows before a checksummed manifest",async()=>{const weighted=buildWeightedConsensusFeeds(collected.feeds);assert.deepEqual(Object.keys(weighted),["consensus"]);assert.equal(weighted.consensus.PPR.players[0].points>0,true);const publication=buildProjectionPublication({collected,policy:policy("allowed-for-redistribution"),draftGoblinArtifact:owned,now:NOW}),published=JSON.parse(publication.bytes),directory=fs.mkdtempSync(path.join(os.tmpdir(),"projection-feed-"));assert.deepEqual(Object.keys(published.feeds).sort(),["consensus","draftGoblin"]);assert.equal(JSON.stringify(published).includes("fantasyPros"),false);assert.equal(JSON.stringify(published).includes("sleeper"),false);try{const output=writeProjectionPublication(publication,directory),bytes=fs.readFileSync(output.snapshotPath);assert.equal(await sha256Hex(bytes),publication.manifest.bundle.sha256);assert.equal(JSON.parse(fs.readFileSync(output.manifestPath,"utf8")).bundle.snapshotId,publication.snapshotId);assert.throws(()=>writeProjectionPublication(publication,directory),/EEXIST/)}finally{fs.rmSync(directory,{recursive:true,force:true})}});
