import test from"node:test";
import assert from"node:assert/strict";
import{allowedProjectionFeedUrl,cachedProjectionFeed,PROJECTION_FEED_MANIFEST_SCHEMA,PROJECTION_FEED_SCHEMA,PROJECTION_FEED_STORAGE_KEY,projectionResponseFromFeed,refreshProjectionFeed,sha256Hex,validateProjectionFeed}from"../extension/projection-feed.js";

const NOW=Date.parse("2026-07-15T12:00:00.000Z"),positions=["QB","RB","WR","TE"],players=(season=2026,scoring="PPR")=>Array.from({length:160},(_,index)=>({id:`p${index}`,name:`Player ${index}`,position:positions[index%positions.length],team:"BUF",points:100+index,season,scoring})),formats=(source,fetchedAt,delta=0,projectionVariant=null)=>Object.fromEntries(["STD","HALF","PPR"].map(scoring=>[scoring,{source,...(projectionVariant?{projectionVariant,modelVersion:"market-shadow-test"}:{}),season:2026,scoring,fetchedAt,players:players(2026,scoring).map(player=>({...player,points:player.points+delta}))}]));
const FEED_BASE="https://coolstick784.github.io/draft-goblin-projections/projections/",bundle=(overrides={})=>({schemaVersion:PROJECTION_FEED_SCHEMA,generatedAt:"2026-07-15T11:00:00.000Z",sourceFetchedAt:"2026-07-15T10:00:00.000Z",feeds:{consensus:formats("Draft Goblin conservative owned ensemble","2026-07-15T10:00:00.000Z"),draftGoblin:formats("Draft Goblin market-adjusted shadow","2026-07-15T10:30:00.000Z",-10,"market-adjusted-shadow-v2")},...overrides});
class Storage{constructor(value={}){this.value={...value}}async get(key){return{[key]:this.value[key]}}async set(patch){Object.assign(this.value,structuredClone(patch))}}
const response=({url,body,status=200,json=false})=>({ok:status>=200&&status<300,status,url,async json(){return json?body:JSON.parse(body)},async arrayBuffer(){return new TextEncoder().encode(json?JSON.stringify(body):body).buffer}});

test("remote feed validation requires fresh source timestamps and same-season players",()=>{assert.equal(validateProjectionFeed(bundle(),{now:NOW}).valid,true);assert.ok(validateProjectionFeed(bundle({sourceFetchedAt:"2026-07-13T00:00:00.000Z"}),{now:NOW}).errors.includes("stale-source-data"));const wrong=bundle();wrong.feeds.consensus.PPR.players[0].season=2025;assert.ok(validateProjectionFeed(wrong,{now:NOW}).errors.some(error=>error.includes("invalid-player")))});
test("projection feed URLs are pinned to the exact HTTPS Pages path",()=>{assert.equal(allowedProjectionFeedUrl(`${FEED_BASE}snapshots/a.json`),true);for(const url of["http://coolstick784.github.io/draft-goblin-projections/projections/a.json","https://coolstick784.github.io.evil.test/draft-goblin-projections/projections/a.json","https://coolstick784.github.io/other/a.json","data:application/json,{}"] )assert.equal(allowedProjectionFeedUrl(url),false)});
test("valid checksummed downloads rotate two durable versions and resolve both daily public feeds",async()=>{const storage=new Storage(),payload=`${JSON.stringify(bundle())}\n`,digest=await sha256Hex(payload),snapshotUrl=`${FEED_BASE}snapshots/pf_one.json`,manifest={schemaVersion:PROJECTION_FEED_MANIFEST_SCHEMA,generatedAt:"2026-07-15T11:00:00.000Z",expiresAt:"2026-07-16T13:00:00.000Z",bundle:{snapshotId:"pf_one",url:snapshotUrl,sha256:digest,bytes:new TextEncoder().encode(payload).length}},fetchImpl=async url=>String(url).includes("manifest.json")?response({url:String(url),body:manifest,json:true}):response({url:snapshotUrl,body:payload});const result=await refreshProjectionFeed({fetchImpl,storage,now:NOW,force:true}),cached=await cachedProjectionFeed({storage,now:NOW});assert.equal(result.snapshotId,"pf_one");assert.equal(projectionResponseFromFeed(cached,"/v1/projections/consensus?scoring=PPR").access,"remote-snapshot");assert.equal(projectionResponseFromFeed(cached,"/v1/projections/draftgoblin?scoring=PPR").access,"remote-snapshot");assert.equal(projectionResponseFromFeed(cached,"/v1/projections/fantasypros?scoring=PPR"),null);assert.equal(storage.value[PROJECTION_FEED_STORAGE_KEY].length,1)});
test("a newer daily manifest atomically advances both feeds and retains one rollback version",async()=>{const priorBundle=validateProjectionFeed(bundle(),{now:NOW}).bundle,storage=new Storage({[PROJECTION_FEED_STORAGE_KEY]:[{snapshotId:"pf_prior",downloadedAt:NOW-1000,bundle:priorBundle}]}),next=bundle({generatedAt:"2026-07-15T11:30:00.000Z"});next.feeds.draftGoblin.PPR.players[0].points=777;next.feeds.consensus.PPR.players[0].points=888;const payload=`${JSON.stringify(next)}\n`,digest=await sha256Hex(payload),snapshotUrl=`${FEED_BASE}snapshots/pf_next.json`,manifest={schemaVersion:PROJECTION_FEED_MANIFEST_SCHEMA,generatedAt:"2026-07-15T11:30:00.000Z",expiresAt:"2026-07-16T13:00:00.000Z",bundle:{snapshotId:"pf_next",url:snapshotUrl,sha256:digest,bytes:new TextEncoder().encode(payload).length}},fetchImpl=async url=>String(url).includes("manifest.json")?response({url:String(url),body:manifest,json:true}):response({url:snapshotUrl,body:payload});await refreshProjectionFeed({fetchImpl,storage,now:NOW,force:true});const versions=storage.value[PROJECTION_FEED_STORAGE_KEY],cached=await cachedProjectionFeed({storage,now:NOW});assert.deepEqual(versions.map(value=>value.snapshotId),["pf_next","pf_prior"]);assert.equal(projectionResponseFromFeed(cached,"/v1/projections/draftgoblin?scoring=PPR").players[0].points,777);assert.equal(projectionResponseFromFeed(cached,"/v1/projections/consensus?scoring=PPR").players[0].points,888)});
test("remote feed rejects raw provider rows, missing Draft Goblin, or incomplete scoring formats",()=>{const raw=bundle();raw.feeds={fantasyPros:raw.feeds.consensus,draftGoblin:raw.feeds.draftGoblin};assert.ok(validateProjectionFeed(raw,{now:NOW}).errors.includes("draft-goblin-required-and-no-raw-providers"));const missing=bundle();delete missing.feeds.draftGoblin;assert.ok(validateProjectionFeed(missing,{now:NOW}).errors.includes("draft-goblin-required-and-no-raw-providers"));const empty=bundle();empty.feeds.draftGoblin={};assert.ok(validateProjectionFeed(empty,{now:NOW}).errors.includes("draftGoblin:PPR:missing-feed"));const partial=bundle();delete partial.feeds.consensus.HALF;assert.ok(validateProjectionFeed(partial,{now:NOW}).errors.includes("consensus:HALF:missing-feed"));const draftGoblinOnly=bundle();delete draftGoblinOnly.feeds.consensus;assert.equal(validateProjectionFeed(draftGoblinOnly,{now:NOW}).valid,true)});
test("remote feed rejects an unadjusted Draft Goblin model",()=>{const unadjusted=bundle();delete unadjusted.feeds.draftGoblin.PPR.projectionVariant;assert.ok(validateProjectionFeed(unadjusted,{now:NOW}).errors.includes("draftGoblin:PPR:market-adjusted-shadow-required"))});
test("tampering never displaces the last known good snapshot",async()=>{const good={snapshotId:"good",downloadedAt:NOW,bundle:validateProjectionFeed(bundle(),{now:NOW}).bundle},storage=new Storage({[PROJECTION_FEED_STORAGE_KEY]:[good]}),payload=`${JSON.stringify(bundle())}\n`,snapshotUrl=`${FEED_BASE}snapshots/bad.json`,manifest={schemaVersion:PROJECTION_FEED_MANIFEST_SCHEMA,generatedAt:"2026-07-15T11:30:00.000Z",expiresAt:"2026-07-16T13:00:00.000Z",bundle:{snapshotId:"bad",url:snapshotUrl,sha256:"0".repeat(64),bytes:new TextEncoder().encode(payload).length}},fetchImpl=async url=>String(url).includes("manifest.json")?response({url:String(url),body:manifest,json:true}):response({url:snapshotUrl,body:payload});await assert.rejects(()=>refreshProjectionFeed({fetchImpl,storage,now:NOW,force:true}),/checksum/);assert.deepEqual(storage.value[PROJECTION_FEED_STORAGE_KEY].map(value=>value.snapshotId),["good"])});
