import test from"node:test";
import assert from"node:assert/strict";
import{projectionConsensus,projectionSourceSummary,PROJECTION_SOURCES}from"../extension/projection-consensus.js";
test("blends the live draft site with current-season FantasyPros using transparent quality weights",()=>{const result=projectionConsensus({season:2026,platform:"sleeper",platformProjection:200,sources:{fantasyPros:{points:220,season:2026,kind:"public-html"}}}),fantasyPros=result.sources.find(source=>source.key==="fantasyPros"),sleeper=result.sources.find(source=>source.key==="sleeper");assert.equal(result.draftSiteProjection,200);assert.deepEqual(result.sources.map(source=>source.key),PROJECTION_SOURCES.map(source=>source.key));assert.equal(fantasyPros.available,true);assert.ok(fantasyPros.weight>sleeper.weight);assert.equal(Number((fantasyPros.weight+sleeper.weight).toFixed(8)),1);assert.equal(result.points,210.49);assert.equal(result.method,"quality-weighted current-season consensus");assert.match(result.weightEvidence,/2022 PPR/);assert.equal(fantasyPros.calibrationStatus,"provisional")});
test("season-mismatched candidate projections receive zero weight",()=>{const result=projectionConsensus({season:2026,platform:"espn",platformProjection:240,sources:{fantasyPros:{points:250,season:2025}}}),source=result.sources.find(item=>item.key==="fantasyPros");assert.equal(source.available,false);assert.equal(source.weight,0);assert.equal(source.unavailableReason,"season mismatch");assert.equal(result.points,240)});
test("uses a current independent source when the draft site has no projection",()=>{const result=projectionConsensus({season:2026,platform:"espn",platformProjection:0,sources:{fantasyPros:{points:250,season:2026,kind:"public-html"}}});assert.equal(result.draftSiteProjection,null);assert.equal(result.points,250);assert.equal(result.sources.find(source=>source.key==="fantasyPros").weight,1)});
test("combines ESPN Sleeper and FantasyPros without dropping the valid ESPN source",()=>{const result=projectionConsensus({season:2026,platform:"espn",platformProjection:220,sources:{espn:{points:999,season:2025},sleeper:{points:215,season:2026,kind:"cross-platform-draft-site"},fantasyPros:{points:230,season:2026,kind:"official-api"}}}),espn=result.sources.find(source=>source.key==="espn"),sleeper=result.sources.find(source=>source.key==="sleeper"),fantasyPros=result.sources.find(source=>source.key==="fantasyPros");assert.equal(espn.available,true);assert.equal(espn.points,220);assert.ok(fantasyPros.weight>espn.weight);assert.ok(espn.weight>sleeper.weight);assert.equal(Number(result.sources.reduce((sum,source)=>sum+source.weight,0).toFixed(8)),1);assert.equal(result.points,222.42)});
test("renormalizes every available-source subset to exactly one",()=>{for(const sources of [{},{sleeper:{points:215,season:2026,kind:"cross-platform-draft-site"}},{fantasyPros:{points:230,season:2026,kind:"public-html"}},{sleeper:{points:215,season:2026,kind:"cross-platform-draft-site"},fantasyPros:{points:230,season:2026,kind:"public-html"}}]){const result=projectionConsensus({season:2026,platform:"espn",platformProjection:220,sources});assert.equal(Number(result.sources.reduce((sum,source)=>sum+source.weight,0).toFixed(10)),1);for(const source of result.sources)assert.equal(source.weight>0,source.available)}});
test("card summary lists every available projection once and hides unavailable feeds",()=>{const result=projectionConsensus({season:2026,platform:"espn",platformProjection:220,sources:{sleeper:{points:215,season:2026,kind:"cross-platform-draft-site"},fantasyPros:{points:230,season:2026,kind:"public-html"}}}),summary=projectionSourceSummary(result);assert.equal(summary,"Consensus: 222.3 · Sleeper: 215.0 · ESPN: 220.0 · FantasyPros: 230.0");for(const label of ["Sleeper","ESPN","FantasyPros"])assert.equal(summary.split(`${label}:`).length-1,1);const espnOnly=projectionConsensus({season:2026,platform:"espn",platformProjection:220});assert.equal(projectionSourceSummary(espnOnly),"Consensus: 220.0 · ESPN: 220.0")});
