import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { pathToFileURL } from "node:url";
import { assessProjectionSnapshot, projectionSnapshotFromState, projectionSnapshotsFromState, ProjectionSnapshotStore } from "../server/projection-snapshots.js";

const state = (overrides = {}) => ({ platform: "espn", projectionSeason: 2026, settings: { scoring: { reception: 1 } }, players: Array.from({ length: 24 }, (_, index) => ({ id: `p${index}`, name: `Player ${index}`, position: index % 2 ? "WR" : "RB", team: "BUF", platformProjection: 100 + index })), ...overrides });
test("snapshot is content-addressed and collection acceptance is not mislabeled leakage certification", () => { const a = projectionSnapshotFromState(state(), { capturedAt: "2026-07-01T12:00:00.000Z" }), b = projectionSnapshotFromState(state(), { capturedAt: "2026-07-01T12:00:00.000Z" }), assessment = assessProjectionSnapshot(a, { now: Date.parse("2026-07-02") }); assert.equal(a.snapshotId, b.snapshotId); assert.equal(a.scoring, "PPR"); assert.equal(a.players[0].projectionSeason, 2026); assert.equal(assessment.valid, true); assert.equal(assessment.deadlineChecked, false); assert.equal(assessment.promotableInput, false); });
test("collector separates independent consensus sources instead of snapshotting only the blended mean", () => { const withSources = state({ players: state().players.map(player => ({ ...player, projectionConsensus: { sources: [{ key: "espn", available: true, points: player.platformProjection }, { key: "fantasyPros", available: true, points: player.platformProjection + 4 }] } })) }), snapshots = projectionSnapshotsFromState(withSources, { capturedAt: "2026-07-01T12:00:00.000Z" }); assert.deepEqual(snapshots.map(snapshot => snapshot.platform), ["espn", "fantasyPros"]); assert.equal(snapshots[1].players[0].points, snapshots[0].players[0].points + 4); });
test("integrity rejects leakage, scoring mismatch, duplicate identity, and all-zero feeds", () => { const snapshot = projectionSnapshotFromState(state({ players: Array.from({ length: 24 }, (_, index) => ({ id: "same", name: `Player ${index}`, position: "WR", platformProjection: 0 })) }), { capturedAt: "2026-09-02T00:00:00.000Z" }); const result = assessProjectionSnapshot(snapshot, { now: Date.parse("2026-09-03"), forecastDeadlineAt: "2026-09-01T00:00:00.000Z", expectedScoring: "STD" }); assert.equal(result.valid, false); assert.ok(result.errors.includes("projection-leakage-after-forecast-deadline")); assert.ok(result.errors.includes("scoring-format-mismatch")); assert.ok(result.errors.includes("duplicate-player-identity")); assert.ok(result.errors.includes("all-or-nearly-all-zero-projections")); });
test("store writes immutable files, deduplicates, and enforces bounded retention", () => { const directoryPath = fs.mkdtempSync(path.join(os.tmpdir(), "dc-snapshots-")), directory = pathToFileURL(`${directoryPath}${path.sep}`), store = new ProjectionSnapshotStore({ directory, maxFiles: 2, maxPerSeries: 2, maxBytes: 1e7 }); try { for (let day = 1; day <= 3; day++) { const snapshot = projectionSnapshotFromState(state(), { capturedAt: `2026-07-0${day}T12:00:00.000Z` }); assert.equal(store.write(snapshot).written, true); } assert.equal(store.files().length, 2); const retained = JSON.parse(fs.readFileSync(store.files()[0].path, "utf8")); assert.equal(retained.collectionIntegrity.valid, true); assert.equal(retained.collectionIntegrity.promotableInput, false); } finally { fs.rmSync(directoryPath, { recursive: true, force: true }); } });
