import test from"node:test";import assert from"node:assert/strict";import{once}from"node:events";import{server,refinementStats,setRefinementDeadlineForTests}from"../server/index.js";import{fixtureState,shaheedPick128State,shaheedPick128OnClockState}from"./fixture.js";
test("API supports health, catalog, evaluation, accounts, and preference sync",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,email=`test-${Date.now()}@example.com`;
  try{
    const health=await fetch(`${base}/health`).then(r=>r.json());assert.equal(health.ok,true);assert.ok(Number.isFinite(health.sourceMtimeMs));assert.equal(health.refinementDeadlineMs,25000);
    const catalog=await fetch(`${base}/v1/catalog`).then(r=>r.json());assert.ok(catalog.players.length>1000);assert.equal(catalog.distributionCalibration.status,"research-not-runtime-wired");assert.equal(catalog.distributionCalibration.dataQuality.promotionGatePassed,false);
    const sleeper=await fetch(`${base}/v1/projections/sleeper?season=2026&scoring=PPR`).then(r=>r.json());assert.equal(sleeper.available,true);assert.ok(sleeper.players.length>200);assert.ok(sleeper.players.every(player=>player.season===2026&&player.points>0));
    const evaluationBody=JSON.stringify({state:fixtureState(),userSlot:1,iterations:20}),evaluation=await fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"test-install"},body:evaluationBody});assert.equal(evaluation.status,200);const evaluationResult=await evaluation.json();assert.ok(evaluationResult.recommendations.length);assert.equal(evaluationResult.calibrated,false);const liveCard=evaluationResult.recommendations[0];for(const value of [liveCard.simulation.championshipProbability,liveCard.simulation.projectedFinalChampionshipProbability,liveCard.teamSimulation.championshipProbability,liveCard.teamSimulation.projectedFinalChampionshipProbability])assert.ok(Number.isFinite(value)&&value>=0&&value<=1);assert.ok(Number.isFinite(liveCard.simulation.calibratedChampionshipProbability));const cached=await fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"test-install"},body:evaluationBody}).then(r=>r.json());assert.equal(cached.cached,true);
    const registration=await fetch(`${base}/v1/auth/register`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({email,password:"long-password-123"})});assert.equal(registration.status,201);const{token}=await registration.json();
    const preferences=await fetch(`${base}/v1/preferences`,{method:"PUT",headers:{"content-type":"application/json",authorization:`Bearer ${token}`},body:JSON.stringify({strategy:"safe",sourceIds:["owned"]})});assert.equal(preferences.status,200);
    const me=await fetch(`${base}/v1/me`,{headers:{authorization:`Bearer ${token}`}}).then(r=>r.json());assert.equal(me.email,email);assert.equal(me.preferences.strategy,"safe");
    const deletion=await fetch(`${base}/v1/account`,{method:"DELETE",headers:{authorization:`Bearer ${token}`}});assert.equal(deletion.status,204);const after=await fetch(`${base}/v1/me`,{headers:{authorization:`Bearer ${token}`}});assert.equal(after.status,401);
  }finally{server.close();await once(server,"close")}
});

test("evaluation refines to a larger cached simulation in a background worker",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,body=JSON.stringify({state:fixtureState({picked:1}),userSlot:1,iterations:120,refineIterations:1000}),start=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":`refine-${Date.now()}`},body}).then(response=>response.json()),poll=evaluationId=>fetch(`${base}/v1/evaluate/${evaluationId}`).then(response=>response.json());
  try{let result=await start();const evaluationId=result.evaluationId;assert.match(evaluationId,/^[a-f0-9]{24}$/);assert.equal(result.status,"refining");assert.equal(result.simulationStatus,"refining");assert.equal(result.targetIterations,1000);const healthStart=performance.now(),health=await fetch(`${base}/health`).then(response=>response.json());assert.equal(health.ok,true);assert.equal(health.clientBuildId,"eval-jobs-v6-strict10k-20260714");assert.match(health.simulationModelVersion,/no-lineup-oracle/);assert.ok(health.activeEvaluationCount>=1);assert.ok(performance.now()-healthStart<500);const deadline=Date.now()+20000;while(result.status==="refining"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await poll(evaluationId)}assert.equal(result.evaluationId,evaluationId);assert.equal(result.status,"complete");assert.equal(result.simulationStatus,"refined");assert.equal(result.iterations,1000);assert.ok(result.recommendations.every(item=>item.simulation.iterations===1000&&Number.isFinite(item.simulation.planChampionshipProbability)&&Number.isFinite(item.simulation.conditionalChampionshipProbability)));assert.ok(result.recommendations.every(item=>item.simulation.candidateSelectionProbability===1));assert.ok(result.recommendations.some(item=>item.nextPickAvailability<1));assert.equal(result.recommendations[0].simulation.championshipProbability,result.recommendations[0].simulation.displayChampionshipProbability)}finally{server.close();await once(server,"close")}
});
test("exact evaluation status polling does not consume the generic 120 request allowance",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,installationId=`status-poll-${Date.now()}`,state=fixtureState({teams:4,rounds:6,picked:1});state.draftId=installationId;
  try{const started=await fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":installationId},body:JSON.stringify({state,userSlot:1,iterations:5,refineIterations:5,limit:2,consumer:"gui"})});assert.equal(started.status,200);const{evaluationId}=await started.json();for(let index=0;index<130;index++){const response=await fetch(`${base}/v1/evaluate/${evaluationId}`,{headers:{"x-installation-id":installationId}});assert.equal(response.status,200,`status poll ${index+1} should not be rate limited`)}const healthResponse=await fetch(`${base}/health`,{headers:{"x-installation-id":installationId}});assert.equal(healthResponse.status,200);const health=await healthResponse.json();assert.ok(health.evaluationDiagnostics.rateLimits.evaluationStatusRequests>=130);assert.equal(health.evaluationDiagnostics.rateLimits.evaluationStatusRejected,0);assert.equal(health.evaluationDiagnostics.rateLimits.evaluationStatusCapacityPerMinute,600);const diagnostic=health.evaluationDiagnostics.recentEvaluations.find(item=>item.evaluationId===evaluationId);assert.equal(diagnostic.status,"complete");assert.equal(diagnostic.terminal,true);assert.equal(diagnostic.consumer,"gui");assert.equal(diagnostic.iterations,5)}finally{server.close();await once(server,"close")}
});
test("refinement deadline publishes usable simulated fallback and cleans up workers",async()=>{
  setRefinementDeadlineForTests(50);server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:12,rounds:16,picked:0});state.draftId=`deadline-${Date.now()}`;const body=JSON.stringify({state,userSlot:1,iterations:120,refineIterations:10000}),request=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":`deadline-${state.draftId}`},body}).then(response=>response.json());
  try{let result=await request(),started=performance.now();const evaluationId=result.evaluationId;assert.equal(result.simulationStatus,"refining");assert.ok(result.recommendations.every(item=>item.simulation&&Number.isFinite(item.simulation.championshipProbability)));const deadline=Date.now()+2000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,20));result=await fetch(`${base}/v1/evaluate/${evaluationId}`).then(response=>response.json())}assert.equal(result.simulationStatus,"refined");assert.equal(result.refinementOutcome,"deadline_fallback");assert.equal(result.iterations,120);assert.ok(performance.now()-started<2000);assert.ok(result.recommendations.length>0);assert.ok(result.recommendations.every(item=>item.simulation&&Number.isFinite(item.simulation.championshipProbability)));const cleanupDeadline=Date.now()+1000;while(refinementStats().jobs&&Date.now()<cleanupDeadline)await new Promise(resolve=>setTimeout(resolve,10));assert.equal(refinementStats().jobs,0);assert.equal(refinementStats().activeWorkers,0);const health=await fetch(`${base}/health`).then(response=>response.json()),diagnostic=health.evaluationDiagnostics.recentEvaluations.find(item=>item.evaluationId===evaluationId);assert.equal(diagnostic.status,"deadline_fallback");assert.equal(diagnostic.terminal,true);assert.equal(diagnostic.consumer,"gui");assert.equal(diagnostic.activeWorkers,0);assert.ok(health.evaluationDiagnostics.statusCounts.deadline_fallback>=1);assert.equal(health.evaluationDiagnostics.pressure.activeEvaluations,0);assert.equal(health.evaluationDiagnostics.pressure.activeWorkers,0)}finally{setRefinementDeadlineForTests(null);server.close();await once(server,"close")}
});
test("fully refined mode can opt out of the fallback deadline",async()=>{
  setRefinementDeadlineForTests(10);server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:10,rounds:15,picked:1});state.draftId=`no-deadline-${Date.now()}`;const body=JSON.stringify({state,userSlot:1,iterations:120,refineIterations:1000,refinementDeadline:false}),request=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":`no-deadline-${state.draftId}`},body}).then(response=>response.json());
  try{let result=await request();assert.equal(result.simulationStatus,"refining");assert.equal(result.refinementDeadlineEnabled,false);const deadline=Date.now()+20000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,50));result=await request()}assert.equal(result.simulationStatus,"refined");assert.equal(result.refinementOutcome,"complete");assert.equal(result.iterations,1000);assert.equal(result.refinementDeadlineEnabled,false)}finally{setRefinementDeadlineForTests(null);server.close();await once(server,"close")}
});
test("refined pick 128 API evidence keeps Shaheed ahead of the tied RB depth",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=shaheedPick128State(),body=JSON.stringify({state,userSlot:state.userSlot,iterations:120,refineIterations:300,limit:8}),request=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":`shaheed-pick-128-${state.draftId}`},body}).then(response=>response.json());
  try{let result=await request(),deadline=Date.now()+30000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await request()}assert.equal(result.simulationStatus,"refined");assert.equal(result.iterations,300);assert.equal(result.recommendations.length,8);assert.equal(result.recommendations[0].player.name,"Rashid Shaheed");const shaheed=result.recommendations.findIndex(item=>item.player.name==="Rashid Shaheed"),tracy=result.recommendations.findIndex(item=>item.player.name==="Tyrone Tracy"),shaheedCard=result.recommendations[shaheed],tracyCard=result.recommendations[tracy];assert.ok(shaheed>=0&&tracy>=0&&shaheed<tracy);assert.ok(result.recommendations.every(item=>item.waitingForUserPick&&item.availabilityTargetPick===128));assert.ok(result.recommendations.every(item=>Number.isFinite(item.simulation.displayChampionshipProbability)));assert.ok(["supported","indistinguishable"].includes(shaheedCard.simulation.evidenceStatus));assert.equal(tracyCard.simulation.evidenceStatus,"indistinguishable")}finally{server.close();await once(server,"close")}
});
test("clock-priority on-clock quick API keeps Shaheed ahead of Tracy",async()=>{server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=shaheedPick128OnClockState(),body=JSON.stringify({state,userSlot:state.userSlot,iterations:120,refineIterations:120,limit:8,clockPriority:true}),result=await fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":`clock-priority-shaheed-${state.draftId}`},body}).then(response=>response.json());try{assert.equal(result.simulationStatus,"quick");assert.equal(result.iterations,120);assert.equal(result.recommendations[0].player.name,"Rashid Shaheed");assert.ok(result.recommendations.findIndex(item=>item.player.name==="Rashid Shaheed")<result.recommendations.findIndex(item=>item.player.name==="Tyrone Tracy"));assert.ok(result.recommendations.every(item=>!item.waitingForUserPick&&item.simulation.candidateSelectionProbability===1))}finally{server.close();await once(server,"close")}});
test("evaluation identity covers every result-affecting request field and rejects build mismatch",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:4,rounds:6,picked:1});state.draftId=`identity-${Date.now()}`;state.draftRunId="run-a";const request=body=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"identity-test"},body:JSON.stringify({state,userSlot:1,iterations:5,refineIterations:5,limit:2,seed:11,strategy:"balanced",positions:["RB"],consumer:"gui",clientBuildId:"eval-jobs-v6-strict10k-20260714",...body})});
  try{const baseline=await request({}),baselineResult=await baseline.json();assert.equal(baseline.status,200);const variants=[{limit:3},{iterations:6,refineIterations:6},{seed:12},{strategy:"safe"},{positions:["WR"]},{state:{...structuredClone(state),draftRunId:"run-b"}}];for(const variant of variants){const response=await request(variant),result=await response.json();assert.equal(response.status,200);assert.notEqual(result.evaluationId,baselineResult.evaluationId)}const mismatch=await request({clientBuildId:"old-build"});assert.equal(mismatch.status,409);assert.match((await mismatch.json()).error,/build mismatch/i)}finally{server.close();await once(server,"close")}
});
test("a new recommendation window cancels stale same-draft refinement work instead of stacking worker pools",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,request=body=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"single-refinement-test"},body:JSON.stringify(body)}).then(response=>response.json()),stale=fixtureState({teams:12,rounds:16,picked:0}),current=fixtureState({teams:12,rounds:16,picked:170}),draftId=`same-draft-${Date.now()}`;stale.draftId=draftId;current.draftId=draftId;
  try{await request({state:stale,userSlot:3,iterations:120,refineIterations:10000});let result=await request({state:current,userSlot:3,iterations:120,refineIterations:1000}),deadline=Date.now()+2000;while(refinementStats().jobs>1&&Date.now()<deadline)await new Promise(resolve=>setTimeout(resolve,25));assert.equal(refinementStats().jobs,1);deadline=Date.now()+20000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await request({state:current,userSlot:3,iterations:120,refineIterations:1000})}assert.equal(result.simulationStatus,"refined");assert.equal(refinementStats().jobs,0)}finally{server.close();await once(server,"close")}
});
test("returning to a cancelled evaluation requeues refinement instead of leaving an orphaned cache entry",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,installationId=`refinement-return-${Date.now()}`,request=body=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":installationId},body:JSON.stringify(body)}).then(response=>response.json()),first=fixtureState({teams:12,rounds:16,picked:0}),second=fixtureState({teams:12,rounds:16,picked:170}),draftId=`return-${Date.now()}`;first.draftId=draftId;second.draftId=draftId;const firstBody={state:first,userSlot:3,iterations:120,refineIterations:1000},secondBody={state:second,userSlot:3,iterations:120,refineIterations:1000};
  try{assert.equal((await request(firstBody)).simulationStatus,"refining");assert.equal((await request(secondBody)).simulationStatus,"refining");let result=await request(firstBody);assert.equal(result.simulationStatus,"refining");const deadline=Date.now()+30000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await request(firstBody)}assert.equal(result.simulationStatus,"refined");assert.equal(result.iterations,1000);assert.ok(result.recommendations.every(item=>item.simulation?.iterations===1000))}finally{server.close();await once(server,"close")}
});
test("different drafts in one installation refine concurrently without cancelling each other",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,stamp=Date.now(),left=fixtureState({teams:12,rounds:16,picked:1}),right=fixtureState({teams:12,rounds:16,picked:2});left.draftId=`concurrent-left-${stamp}`;right.draftId=`concurrent-right-${stamp}`;const request=(installationId,state)=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":installationId},body:JSON.stringify({state,userSlot:4,iterations:120,refineIterations:1000})}).then(response=>response.json()),leftId=`installation-left-${stamp}`,rightId=`installation-right-${stamp}`;
  try{const sharedId=`installation-shared-${stamp}`;let[leftResult,rightResult]=await Promise.all([request(sharedId,left),request(sharedId,right)]);assert.equal(leftResult.simulationStatus,"refining");assert.equal(rightResult.simulationStatus,"refining");assert.notEqual(leftResult.evaluationId,rightResult.evaluationId);const deadline=Date.now()+30000;while((leftResult.simulationStatus!=="refined"||rightResult.simulationStatus!=="refined")&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));[leftResult,rightResult]=await Promise.all([request(sharedId,left),request(sharedId,right)])}assert.equal(leftResult.simulationStatus,"refined");assert.equal(rightResult.simulationStatus,"refined");assert.equal(leftResult.iterations,1000);assert.equal(rightResult.iterations,1000)}finally{server.close();await once(server,"close")}
});
test("refined kicker cards preserve candidate-specific simulation evidence",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:4,rounds:6,picked:0});state.draftId=`specialist-display-${Date.now()}`;state.settings.slots.K=1;const body=JSON.stringify({state,userSlot:1,positions:["K"],iterations:120,refineIterations:1000}),request=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"specialist-display-test"},body}).then(response=>response.json());
  try{let result=await request(),deadline=Date.now()+20000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await request()}assert.equal(result.simulationStatus,"refined");assert.ok(result.recommendations.length>0);for(const item of result.recommendations){assert.equal(item.player.position,"K");assert.equal(item.simulation.specialistReplacementBaseline,undefined);assert.equal(item.simulation.conditional,true);assert.equal(item.simulation.candidateSelectionProbability,1);assert.ok(Number.isFinite(item.simulation.championshipProbability));assert.ok(Number.isFinite(item.simulation.displayChampionshipProbability))}}finally{server.close();await once(server,"close")}
});
test("live API refinement never recommends depth when three picks must fill three starters",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:10,rounds:9,picked:0}),used=new Set();state.draftId=`forced-completion-${Date.now()}`;state.settings.slots={...state.settings.slots,QB:1,RB:1,WR:1,TE:1,FLEX:0,K:1,DST:1,BENCH:2};state.picks=["QB","RB","WR","RB","WR","RB"].map((position,index)=>{const player=state.players.find(candidate=>candidate.position===position&&!used.has(candidate.id));used.add(player.id);return{pickNo:index+1,playerId:player.id,slot:1}});state.updatedAt=Date.now();const body=JSON.stringify({state,userSlot:1,iterations:120,refineIterations:300}),request=()=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"forced-completion-test"},body}).then(response=>response.json()),assertForced=result=>{assert.ok(result.recommendations.length>0);assert.ok(result.recommendations.every(item=>item.rosterCompletionRequired&&item.remainingPicks===3&&item.missingRequiredSlots===3&&["TE","K","DST"].includes(item.player.position)));const positions=new Set(result.recommendations.map(item=>item.player.position));for(const position of ["TE","K","DST"])assert.ok(positions.has(position),`API omitted ${position}`)};
  try{let result=await request();assertForced(result);const deadline=Date.now()+40000;while(result.simulationStatus!=="refined"&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,100));result=await request()}assert.equal(result.simulationStatus,"refined");assertForced(result)}finally{server.close();await once(server,"close")}
});
test("completed draft report API serves exact scoring and separated decision audits",async()=>{
  server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState({teams:6,rounds:6,picked:36});
  try{const created=await fetch(`${base}/v1/draft-report`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({state,userSlot:1,iterations:1000})});assert.equal(created.status,201);const result=await created.json();assert.match(result.url,/\/reports\//);assert.ok(result.report.grade.score>=0);assert.equal(result.report.userTeam.finishProbabilities.length,6);assert.equal(result.report.userTeam.draft.length,6);assert.ok(Number.isFinite(result.report.userTeam.pointsExact));assert.ok(result.report.userTeam.titleRank>=1&&result.report.userTeam.titleRank<=6);assert.equal(result.report.decisionAudit.contemporaneous.label,"Captured decision context");assert.equal(result.report.decisionAudit.hindsight.label,"Bounded title-odds hindsight");const page=await fetch(result.url.replace("localhost", "127.0.0.1").replace(":8787",`:${server.address().port}`));assert.equal(page.status,200);assert.equal(page.headers.get("cache-control"),"no-store");const html=await page.text();assert.match(html,/Draft Goblin report/);assert.match(html,/Your draft/);assert.match(html,/Championship outlook/);assert.match(html,/Overall draft grade/);assert.match(html,/Title odds only/);assert.doesNotMatch(html,/Blends title outlook, weekly scoring/);assert.match(html,/How to read this result/);assert.doesNotMatch(html,/Your projected finish/);assert.doesNotMatch(html,/Captured decision context/);assert.doesNotMatch(html,/Bounded title-odds hindsight/);assert.doesNotMatch(html,/Strongest multi-pick route tested/);assert.doesNotMatch(html,/[^\x00-\x7f]/)}finally{server.close();await once(server,"close")}
});
test("evaluation cache invalidates when projections, distributions, player semantics, or pick assignments change",async()=>{server.listen(0);await once(server,"listening");const base=`http://127.0.0.1:${server.address().port}`,state=fixtureState();state.draftId=`cache-key-${Date.now()}`;const request=value=>fetch(`${base}/v1/evaluate`,{method:"POST",headers:{"content-type":"application/json","x-installation-id":"cache-key-test"},body:JSON.stringify({state:value,userSlot:1,iterations:20})}).then(response=>response.json());try{await request(state);const projectionChanged=structuredClone(state);projectionChanged.players[0].mean+=25;projectionChanged.updatedAt=Date.now();assert.notEqual((await request(projectionChanged)).cached,true);const distributionChanged=structuredClone(projectionChanged);distributionChanged.players[0].distribution={version:1,probabilities:[0,.5,1],values:[0,distributionChanged.players[0].mean,distributionChanged.players[0].mean*2]};assert.notEqual((await request(distributionChanged)).cached,true);distributionChanged.players[0].distribution.values[0]=1;assert.notEqual((await request(distributionChanged)).cached,true);const semanticsChanged=structuredClone(distributionChanged);semanticsChanged.players[0].risk+=.1;semanticsChanged.players[0].scarcity+=.1;semanticsChanged.updatedAt=Date.now();assert.notEqual((await request(semanticsChanged)).cached,true);const assignmentChanged=structuredClone(semanticsChanged);assignmentChanged.picks[0].slot=assignmentChanged.picks[0].slot===1?2:1;assignmentChanged.updatedAt=Date.now();assert.notEqual((await request(assignmentChanged)).cached,true)}finally{server.close();await once(server,"close")}});
