import test from "node:test";
import assert from "node:assert/strict";
import { aggregateWeeklySeasons, backtestWeeklyToSeasonDistributions, evaluateSeasonRatioRanges, evaluateWeeklyToSeasonRanges, fitWeeklyToSeasonModel } from "../scripts/backtest-weekly-to-season-distributions.js";

function fixture(){const rows=[];for(const year of[2021,2022,2023,2024])for(let player=0;player<18;player++)for(let week=1;week<=12;week++){const projected=8+(player%3),volatile=player<9,zero=volatile&&(week+player)%5===0,multiplier=volatile?((week+player)%3===0?.3:1.8):(.9+((week+player)%3)*.1),actual=zero?0:projected*multiplier;rows.push({sourceId:"test",year,week,playerId:String(player),name:`Player ${player}`,position:"WR",projected,actual})}return rows}

test("weekly seasons preserve zero observations and chronological week blocks",()=>{const seasons=aggregateWeeklySeasons(fixture().filter(row=>row.year===2021));assert.equal(seasons.length,18);assert.equal(seasons[0].weeks.length,12);assert.ok(seasons.some(row=>row.zeroWeeks>0));assert.deepEqual(seasons[0].weeks.map(row=>row.week),[1,2,3,4,5,6,7,8,9,10,11,12])});

test("two-part model estimates player availability and positive performance separately",()=>{const model=fitWeeklyToSeasonModel(fixture().filter(row=>row.year<=2022),{availabilityShrinkage:32,performanceShrinkage:128}),profile=model.profiles.get("player0:WR");assert.ok(profile.zeroRate>0);assert.ok(profile.availabilityWeight>profile.performanceWeight);assert.equal(profile.weeks,24);assert.ok(profile.positiveWeeks<profile.weeks)});

test("walk-forward backtest keeps 2024 untouched and selects a complete model family on validation WIS",()=>{const artifact=backtestWeeklyToSeasonDistributions(fixture(),{generatedAt:"2026-01-01T00:00:00.000Z",validationSimulations:120,holdoutSimulations:200,bootstrapDraws:100});assert.deepEqual(artifact.selection.validationYears,[2022,2023]);assert.match(artifact.selection.selectionObjective,/season-count-weighted/);assert.ok(["weekly-block-bootstrap","season-ratio-empirical-bayes"].includes(artifact.selection.selectedModelFamily));assert.equal(artifact.holdout.year,2024);assert.equal(artifact.holdout.seasons,18);assert.match(artifact.leakageBoundary,/untouched holdout/);assert.equal(artifact.holdout.seasonBootstrap.seasonClusters,18);assert.ok(artifact.holdout.candidate.coverage>=0&&artifact.holdout.candidate.coverage<=1)});

test("unseen players exactly retain the position-tier baseline",()=>{const rows=fixture(),training=rows.filter(row=>row.year<=2022),testRows=rows.filter(row=>row.year===2023).map(row=>({...row,name:`New ${row.name}`,playerId:`new-${row.playerId}`})),metrics=evaluateWeeklyToSeasonRanges(training,testRows,{simulations:100});assert.equal(metrics.playersWithPrior,0);assert.deepEqual(metrics.candidate,metrics.baseline);assert.equal(metrics.zeroComponent.candidateBrierScore,metrics.zeroComponent.baselineBrierScore)});

test("season-ratio model also falls back exactly for unseen players",()=>{const rows=fixture(),training=rows.filter(row=>row.year<=2022),testRows=rows.filter(row=>row.year===2023).map(row=>({...row,name:`New ${row.name}`})),metrics=evaluateSeasonRatioRanges(training,testRows,{playerShrinkage:24});assert.equal(metrics.playersWithPrior,0);assert.deepEqual(metrics.candidate,metrics.baseline)});
