import test from"node:test";
import assert from"node:assert/strict";
import{backtestWeeklyPlayerRanges,evaluateWeeklyRanges}from"../scripts/backtest-weekly-player-ranges.js";

function fixture(){const rows=[];for(const year of[2021,2022,2023,2024])for(let player=0;player<20;player++)for(let week=1;week<=12;week++){const projected=10+(player%4),spread=player<10?1:6,actual=Math.max(0,projected+((week+player)%3===0?-spread:spread));rows.push({sourceId:"test",year,week,playerId:String(player),name:`Player ${player}`,position:"WR",projected,actual})}return rows}

test("weekly player intervals are leakage-safe and preserve asymmetric quantile order",()=>{const rows=fixture(),metrics=evaluateWeeklyRanges(rows.filter(row=>row.year<=2022),rows.filter(row=>row.year===2023),{shrinkage:4,bootstrapDraws:100});assert.equal(metrics.rows,240);assert.ok(metrics.playersWithPrior>0);assert.ok(metrics.candidate.meanWidth!==metrics.baseline.meanWidth);const artifact=backtestWeeklyPlayerRanges(rows,{generatedAt:"2026-01-01T00:00:00.000Z",bootstrapDraws:100});assert.equal(artifact.selection.validationYear,2023);assert.equal(artifact.holdout.year,2024);assert.match(artifact.leakageBoundary,/untouched holdout/);assert.equal(artifact.holdout.clusterBootstrap.clusters,20)});

test("unseen weekly players retain the position and projection-tier interval",()=>{const rows=fixture(),training=rows.filter(row=>row.year<=2022),testRows=rows.filter(row=>row.year===2023).map(row=>({...row,name:`New ${row.name}`,playerId:`new-${row.playerId}`})),metrics=evaluateWeeklyRanges(training,testRows,{shrinkage:4});assert.equal(metrics.playersWithPrior,0);assert.deepEqual(metrics.candidate,metrics.baseline)});

test("position shrinkage is partially pooled and rolling-origin folds tune before testing",()=>{const artifact=backtestWeeklyPlayerRanges(fixture(),{generatedAt:"2026-01-01T00:00:00.000Z",bootstrapDraws:100}),selection=artifact.selection.positionSelections.WR;assert.ok(selection.evidenceWeight>0&&selection.evidenceWeight<1);assert.ok(selection.selectedShrinkage>=Math.min(selection.rawBestShrinkage,selection.globalShrinkage));assert.ok(selection.selectedShrinkage<=Math.max(selection.rawBestShrinkage,selection.globalShrinkage));assert.deepEqual(artifact.rollingOrigin.folds.map(fold=>[fold.tuningYear,fold.testYear,fold.trainingThrough]),[[2022,2023,2022],[2023,2024,2023]]);assert.deepEqual(artifact.dataQuality.incompleteYearsExcluded,[2025]);assert.equal(artifact.dataQuality.runtimePromotionGatePassed,false)});

test("observed zeros remain scored and are reported separately from positive outcomes",()=>{const rows=fixture();for(let index=0;index<12;index++)rows.find(row=>row.year===2023&&row.week===index+1).actual=0;const metrics=evaluateWeeklyRanges(rows.filter(row=>row.year<=2022),rows.filter(row=>row.year===2023),{shrinkage:32});assert.equal(metrics.outcomeStrata.observedZero.rows,12);assert.equal(metrics.outcomeStrata.positiveOutcome.rows,228);assert.equal(metrics.outcomeStrata.negativeOutcome.rows,0);assert.equal(metrics.outcomeStrata.observedZero.rate,.05);assert.equal(metrics.outcomeStrata.conditionalPositiveModel.testRows,228);assert.match(metrics.outcomeStrata.conditionalPositiveModel.interpretation,/not a played-game model/);assert.ok(metrics.outcomeStrata.observedZero.baseline.weightedIntervalScore>0)});
