import fs from"node:fs";
import{fetchWithRetry}from"./fetch-retry.js";
const CACHE_TTL=6*60*60*1000,FALLBACK_CACHE_TTL=5*60*1000,SNAPSHOT_MAX_AGE=7*24*60*60*1000,cache=new Map(),POSITIONS=["qb","rb","wr","te","k","dst"],snapshotDirectory=new URL("../data/snapshots/",import.meta.url);
export function fantasyProsPoints(payload,scoring="PPR"){const key=String(scoring).toUpperCase(),field=key==="PPR"?"points_ppr":key==="HALF"?"points_half":"points";return (payload?.players||[]).map(player=>({id:String(player.fpid||player.player_id||""),name:player.name||player.player_name,position:player.position_id||player.position,team:player.team_id||player.team,points:Number(player.stats?.[field]??player.stats?.points??0)})).filter(player=>player.name&&player.points>0)}
const clean=value=>String(value||"").replace(/<[^>]+>/g,"").replace(/&amp;/g,"&").replace(/&#039;/g,"'").trim();
export function parseFantasyProsHtml(html,position){const players=[];for(const match of String(html).matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)){const row=match[1],nameMatch=row.match(/fp-player-name="([^"]+)"/i);if(!nameMatch)continue;const id=row.match(/fp-id-(\d+)/i)?.[1]||"",anchorEnd=row.indexOf("</a>"),team=clean(row.slice(anchorEnd+4).match(/^\s*([A-Z]{2,3})\b/)?.[1]||""),cells=[...row.matchAll(/<td[^>]*class="[^"]*center[^"]*"[^>]*>([\s\S]*?)<\/td>/gi)],last=cells.at(-1),sortValue=last?.[0].match(/data-sort-value="([0-9.]+)"/i)?.[1],points=Number(sortValue||clean(last?.[1]).replaceAll(",",""));if(points>0)players.push({id,name:clean(nameMatch[1]),position:String(position).toUpperCase(),team,points})}return players}

const playerIdentity=player=>{const name=String(player.name||"").normalize("NFKD").replace(/\b(?:jr|sr|ii|iii|iv|v)\.?\s*$/i,"").replace(/[^a-z0-9]/gi,"").toLowerCase();return name?`${name}:${String(player.position||"").toUpperCase()}`:String(player.id||"")};
export function mergeFantasyProsCandidates(candidates=[]){const players=[],seenIds=new Set(),seenIdentities=new Set(),supplements=[];for(const candidate of candidates){let added=0;for(const player of candidate?.value?.players||candidate?.players||[]){const id=String(player.id||""),idKey=id?`${id}:${String(player.position||"").toUpperCase()}`:"",identity=playerIdentity(player);if((idKey&&seenIds.has(idKey))||(identity&&seenIdentities.has(identity)))continue;players.push(player);if(idKey)seenIds.add(idKey);if(identity)seenIdentities.add(identity);added++}if(added&&candidate?.name)supplements.push({snapshotFile:candidate.name,snapshotAgeMs:candidate.ageMs,playerCount:added})}return{players,supplements}}
function recentFantasyProsSnapshots({season,scoring,directory,now,maxAgeMs=SNAPSHOT_MAX_AGE}){const scoringKey=String(scoring).toUpperCase(),candidates=[];try{for(const name of fs.readdirSync(directory)){if(!name.startsWith("fantasypros-")||!name.endsWith(".json"))continue;try{const value=JSON.parse(fs.readFileSync(new URL(name,directory),"utf8")),fetchedAt=Date.parse(value.fetchedAt),ageMs=Number(now)-fetchedAt;if(Number(value.season)!==Number(season)||String(value.scoring).toUpperCase()!==scoringKey||!Array.isArray(value.players)||!value.players.length||!Number.isFinite(fetchedAt)||ageMs<0||ageMs>maxAgeMs)continue;candidates.push({value,fetchedAt,ageMs,name})}catch{}}}catch{return[]}return candidates.sort((a,b)=>b.fetchedAt-a.fetchedAt||b.name.localeCompare(a.name))}
function supplementIncompletePositions({players,incompletePositions,candidates}){const supplemented=[],supplements=[];for(const position of incompletePositions){const live=players.filter(player=>String(player.position).toUpperCase()===position),candidate=candidates.find(item=>item.value.players.filter(player=>String(player.position).toUpperCase()===position).length>10);if(!candidate){supplemented.push(...live);continue}const merged=new Map(candidate.value.players.filter(player=>String(player.position).toUpperCase()===position).map(player=>[playerIdentity(player),player]));for(const player of live)merged.set(playerIdentity(player),player);supplemented.push(...merged.values());supplements.push({position,snapshotFile:candidate.name,snapshotAgeMs:candidate.ageMs})}const incomplete=new Set(incompletePositions);return{players:[...players.filter(player=>!incomplete.has(String(player.position).toUpperCase())),...supplemented],supplements}}

async function publicFantasyPros({season,scoring,fetchImpl,captureSnapshot,directory=snapshotDirectory,now=Date.now()}){const scoringKey=String(scoring).toUpperCase(),results=await Promise.allSettled(POSITIONS.map(async position=>{const url=new URL(`https://www.fantasypros.com/nfl/projections/${position}.php`);url.searchParams.set("week","draft");url.searchParams.set("year",String(season));url.searchParams.set("scoring",scoringKey);
  // Prefer the print table, then detect and recover the intermittent ten-row
  // response FantasyPros still returns for individual positions.
  url.searchParams.set("print","true");
  const response=await fetchWithRetry(url,{headers:{"user-agent":"DraftChampion/0.2 projection research"}},{fetchImpl});if(!response.ok)throw new Error(`FantasyPros public ${position.toUpperCase()} projections failed (${response.status})`);const html=await response.text();return{position,url:String(url),players:parseFantasyProsHtml(html,position)}})),pages=results.filter(result=>result.status==="fulfilled").map(result=>result.value),failedPositions=results.flatMap((result,index)=>result.status==="rejected"?[POSITIONS[index].toUpperCase()]:[]);if(!pages.length)throw results[0]?.reason||new Error("FantasyPros public projections were unavailable");const players=pages.flatMap(page=>page.players),truncatedPositions=pages.filter(page=>page.players.length<=10).map(page=>page.position.toUpperCase()),incompletePositions=[...new Set([...failedPositions,...truncatedPositions])],fetchedAt=new Date(now).toISOString(),rawValue={available:players.length>0,partial:incompletePositions.length>0,failedPositions,truncatedPositions,source:"FantasyPros public consensus",access:"public-html",season:Number(season),scoring:scoringKey,fetchedAt,players};if(captureSnapshot)try{fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(new URL(`fantasypros-${season}-${scoringKey}-${fetchedAt.replace(/[:.]/g,"-")}.json`,directory),JSON.stringify(rawValue,null,2))}catch{}const candidates=recentFantasyProsSnapshots({season,scoring:scoringKey,directory,now}),recovered=supplementIncompletePositions({players,incompletePositions,candidates}),recoveredPositions=recovered.supplements.map(item=>item.position),unrecoveredPositions=incompletePositions.filter(position=>!recoveredPositions.includes(position)),merged=mergeFantasyProsCandidates([{players:recovered.players},...candidates]),snapshotRecoveredPlayerCount=merged.players.length-recovered.players.length;return{...rawValue,players:merged.players,recoveredPositions,unrecoveredPositions,snapshotSupplements:merged.supplements,snapshotRecoveredPlayerCount}}

export function latestFantasyProsSnapshot({season,scoring="PPR",directory=snapshotDirectory,now=Date.now(),maxAgeMs=SNAPSHOT_MAX_AGE}){const candidates=recentFantasyProsSnapshots({season,scoring,directory,now,maxAgeMs}),latest=candidates[0];if(!latest)return null;const merged=mergeFantasyProsCandidates(candidates);return{...latest.value,players:merged.players,available:true,access:"local-snapshot-fallback",fallback:true,snapshotAgeMs:latest.ageMs,snapshotFile:latest.name,snapshotFiles:candidates.map(candidate=>candidate.name),snapshotCount:candidates.length,snapshotSupplements:merged.supplements}}

export async function currentFantasyPros({season,scoring="PPR",apiKey=process.env.FANTASYPROS_API_KEY,fetchImpl=fetch,captureSnapshot=true,snapshotDirectory:directory=snapshotDirectory,now=Date.now()}){const cacheKey=`${season}:${scoring}:${apiKey?"api":"public"}`,cached=cache.get(cacheKey);if(cached&&now-cached.at<(cached.ttl||CACHE_TTL))return{...cached.value,cached:true};let value,ttl=CACHE_TTL;try{if(apiKey){const url=new URL(`https://api.fantasypros.com/public/v2/json/nfl/${Number(season)}/projections`);url.searchParams.set("week","0");url.searchParams.set("scoring",String(scoring).toUpperCase());const response=await fetchWithRetry(url,{headers:{"x-api-key":apiKey}},{fetchImpl});if(!response.ok)throw new Error(`FantasyPros projections failed (${response.status})`);const players=fantasyProsPoints(await response.json(),scoring);value={available:players.length>0,source:"FantasyPros official API",access:"official-api",season:Number(season),scoring:String(scoring).toUpperCase(),fetchedAt:new Date(now).toISOString(),players}}else value=await publicFantasyPros({season,scoring,fetchImpl,captureSnapshot,directory,now});if(value.partial)ttl=FALLBACK_CACHE_TTL}catch(cause){const fallback=latestFantasyProsSnapshot({season,scoring,directory,now});if(!fallback)throw cause;value={...fallback,liveFetchError:String(cause?.message||cause)};ttl=FALLBACK_CACHE_TTL}cache.set(cacheKey,{at:now,ttl,value});return value}
