import http from "node:http";import fs from "node:fs";import crypto from"node:crypto";import{Worker}from"node:worker_threads";import{evaluateDraft,rankEvaluatedRecommendations,titleTenths}from"../core/evaluate.js";import{calibrateTitleProbability,pairedDifference,SIMULATION_MODEL_VERSION}from"../core/simulate.js";import{buildCandidateBoard,recommend}from"../core/recommend.js";import{snakeSlot}from"../shared/domain.js";import{projectedOutcome}from"../core/projected-outcome.js";import{currentFantasyPros}from"./fantasypros.js";import{refreshSleeperProjections}from"./sleeper-projections.js";import{capturePlatformSnapshot,projectionSnapshotDiagnostics}from"./projection-snapshots.js";import{DistributionShadowTelemetry,scheduleDistributionShadow}from"./distribution-shadow.js";import{buildDraftReport}from"../core/post-draft-report.js";import{reportPage}from"./report-page.js";import{AuthStore}from"./auth.js";import{chooseWorkerConcurrency}from"./adaptive-scheduler.js";
import{assessRankingReadiness}from"../core/evaluate.js";
import{PersistentReportStore}from"./report-store.js";
import{SharedWorkPool}from"./shared-work-pool.js";
import{FullRefinementScheduler}from"./full-refinement-scheduler.js";
import{playerDistributionFingerprintMaterial}from"../shared/player-distribution.js";
const CLIENT_BUILD_ID="eval-jobs-v1-20260714",PORT=Number(process.env.PORT||8787),baselinePath=new URL("../data/generated/current-baseline.json",import.meta.url),calibrationPath=new URL("../data/research/multi-source-projection-calibration.json",import.meta.url),playerDistributionCalibrationPath=new URL("../data/research/player-weekly-distributions-quantile-v1.json",import.meta.url),liveDeepReplayPath=new URL("../data/generated/live-deep-replay.local.json",import.meta.url),calibrationReport=JSON.parse(fs.readFileSync(calibrationPath,"utf8")),baselineCatalog=fs.existsSync(baselinePath)?JSON.parse(fs.readFileSync(baselinePath,"utf8")):null,playerDistributionCalibration=fs.existsSync(playerDistributionCalibrationPath)?JSON.parse(fs.readFileSync(playerDistributionCalibrationPath,"utf8")):null,baselineQuality=baselineCatalog?.dataQuality||"missing",auth=new AuthStore(),hits=new Map(),evaluationStatusHits=new Map(),evaluationCache=new Map(),evaluationKeyById=new Map(),refinementJobs=new Map(),candidateSimulationCache=new Map(),candidateSimulationInflight=new Map(),activeRefinements=new Map(),sharedRefinementPool=new SharedWorkPool(),fullRefinementScheduler=new FullRefinementScheduler(),stateFingerprintCache=new WeakMap(),reportStore=new PersistentReportStore(),MAX_SIMULATION_CACHE=512,MAX_EVALUATION_CACHE=256,MAX_REFINEMENT_DEADLINE_MS=25000,EVALUATION_RETENTION_MS=120000,EVALUATION_STATUS_RATE_LIMIT=600,MAX_DIAGNOSTIC_EVALUATIONS=32,rateLimitStats={genericRequests:0,genericRejected:0,evaluationStatusRequests:0,evaluationStatusRejected:0};
const SERVER_SOURCE_MTIME_MS=Math.trunc(fs.statSync(new URL(import.meta.url)).mtimeMs);
const CURRENT_CLIENT_BUILD_ID="eval-jobs-v6-strict10k-20260714";
let lastDeepEvaluation=null;
function captureLiveDeepReplay(input,requestBytes){if(process.env.DRAFT_GOBLIN_CAPTURE_DEEP_REPLAY!=="1")return;fs.writeFileSync(liveDeepReplayPath,JSON.stringify({capturedAt:new Date().toISOString(),requestBytes,input}),"utf8")}
const distributionShadowTelemetry=new DistributionShadowTelemetry();
const configuredRefinementDeadline=()=>Math.min(MAX_REFINEMENT_DEADLINE_MS,Math.max(10,Number(process.env.DRAFT_CHAMPION_REFINEMENT_DEADLINE_MS)||MAX_REFINEMENT_DEADLINE_MS));
let refinementDeadlineMs=configuredRefinementDeadline();
function setBounded(cache,key,value,maximum){if(cache.has(key))cache.delete(key);cache.set(key,value);while(cache.size>maximum)cache.delete(cache.keys().next().value)}
const headers={"content-type":"application/json","cache-control":"no-store","access-control-allow-origin":"*","access-control-allow-headers":"content-type,authorization,x-installation-id,x-fantasypros-key"};
const send=(res,status,value)=>{res.writeHead(status,headers);res.end(JSON.stringify(value))};
async function json(req,limit=5_000_000){let body="";for await(const chunk of req){body+=chunk;if(body.length>limit){const error=new Error("request too large");error.code="PAYLOAD_TOO_LARGE";throw error}}try{return JSON.parse(body||"{}")}catch{throw new Error("invalid JSON")}}
const bearer=req=>String(req.headers.authorization||"").replace(/^Bearer\s+/i,"");
function limitedIn(cache,key,capacity){const now=Date.now(),entry=cache.get(key)||{start:now,count:0};if(now-entry.start>60000){entry.start=now;entry.count=0}entry.count++;cache.set(key,entry);if(cache.size>5000)for(const[k,value]of cache)if(now-value.start>120000)cache.delete(k);return entry.count>capacity}
const requestIdentity=req=>`${req.socket.remoteAddress||"unknown"}:${req.headers["x-installation-id"]||"anonymous"}`;
function limited(req,capacity=60){rateLimitStats.genericRequests++;const rejected=limitedIn(hits,requestIdentity(req),capacity);if(rejected)rateLimitStats.genericRejected++;return rejected}
function evaluationStatusLimited(req,evaluationId){rateLimitStats.evaluationStatusRequests++;const rejected=limitedIn(evaluationStatusHits,`${requestIdentity(req)}:${evaluationId}`,EVALUATION_STATUS_RATE_LIMIT);if(rejected)rateLimitStats.evaluationStatusRejected++;return rejected}
function stateFingerprint(state){const cached=stateFingerprintCache.get(state);if(cached)return cached;const projections=state.players.map(player=>`${player.id}:${player.position||""}:${player.team||""}:${Number(player.mean||0).toFixed(2)}:${Number(player.floor||0).toFixed(2)}:${Number(player.ceiling||0).toFixed(2)}:${Number(player.risk||0).toFixed(3)}:${Number(player.scarcity||0).toFixed(3)}:${Number(player.adp||0).toFixed(2)}:${Number(player.adpSd||0).toFixed(2)}:${player.adpSeason||""}:${player.adpTeams||""}:${player.adpScoring||""}:${player.adpProvider||""}:${player.adpFetchedAt||""}:${player.eligibleForRecommendation!==false}:${playerDistributionFingerprintMaterial(player)}`).join("|"),value=crypto.createHash("sha1").update(JSON.stringify([state.platform,state.draftId,state.draftRunId||"",state.picks.map(p=>[p.pickNo,p.playerId,p.slot]),state.settings,state.modelVersion,state.projectionSeason,projections,SIMULATION_MODEL_VERSION])).digest("hex");stateFingerprintCache.set(state,value);return value}
function simulationKey(input,iterations,candidate){return `${input.sharedWorkKey||input.consumer||"gui"}:${stateFingerprint(input.state)}:${input.userSlot}:${iterations}:${input.seed||2026}:${candidate?.id||"__baseline__"}`}
function workerSimulation(input,iterations,candidate,controller){const cacheKey=simulationKey(input,iterations,candidate),cached=candidateSimulationCache.get(cacheKey);if(cached)return Promise.resolve(cached);const pending=candidateSimulationInflight.get(cacheKey);if(pending&&!pending.controller?.cancelled)return pending.promise;if(pending)candidateSimulationInflight.delete(cacheKey);const rawPromise=new Promise((resolve,reject)=>{const worker=new Worker(new URL("./simulation-worker.js",import.meta.url),{workerData:{state:input.state,candidate,userSlot:input.userSlot,iterations,seed:input.seed||2026}});controller?.workers.add(worker);let settled=false,watchdog;const finish=(error,value)=>{if(settled)return;settled=true;clearTimeout(watchdog);controller?.workers.delete(worker);worker.terminate();error?reject(error):resolve(value)};if(controller?.deadlineAt){const remaining=Math.max(1,controller.deadlineAt-Date.now());watchdog=setTimeout(()=>finish(Object.assign(new Error("simulation deadline exceeded"),{code:"REFINEMENT_DEADLINE"})),remaining);watchdog.unref?.()}worker.once("message",message=>{if(!message.ok)return finish(new Error(message.error));Object.defineProperties(message.simulation,{scenarioWins:{value:message.scenarioWins,enumerable:false},planScenarioWins:{value:message.planScenarioWins,enumerable:false},scenarioSelected:{value:message.scenarioSelected,enumerable:false}});setBounded(candidateSimulationCache,cacheKey,message.simulation,MAX_SIMULATION_CACHE);finish(null,message.simulation)});worker.once("error",error=>finish(error));worker.once("exit",code=>{if(!settled)finish(new Error(`simulation worker exited (${code})`))})}),entry={controller,promise:null};entry.promise=rawPromise.finally(()=>{if(candidateSimulationInflight.get(cacheKey)===entry)candidateSimulationInflight.delete(cacheKey)});candidateSimulationInflight.set(cacheKey,entry);return entry.promise}
function workerSimulationChunkPool({input,candidates,chunks,workerCount,controller,onProgress}){
  const progressByShard=new Map(chunks.map(chunk=>[chunk.scenarioOffset,0]));
  return new Promise((resolve,reject)=>{
    const parts=new Array(chunks.length),workers=new Set();let cursor=0,completedChunks=0,settled=false,watchdog;
    const emitProgress=()=>onProgress?.({completed:[...progressByShard.values()].reduce((sum,value)=>sum+value,0),total:chunks.reduce((sum,chunk)=>sum+chunk.iterations,0),workerCount,shardCount:chunks.length});
    const finish=(error)=>{if(settled)return;settled=true;clearTimeout(watchdog);for(const worker of workers){controller?.workers.delete(worker);worker.terminate()}workers.clear();error?reject(error):resolve(parts)};
    const assign=(worker)=>{if(settled)return;const taskId=cursor++;if(taskId>=chunks.length)return;const chunk=chunks[taskId];worker.postMessage({type:"run",taskId,scenarioOffset:chunk.scenarioOffset,iterations:chunk.iterations})};
    if(controller?.deadlineAt){watchdog=setTimeout(()=>finish(Object.assign(new Error("simulation deadline exceeded"),{code:"REFINEMENT_DEADLINE"})),Math.max(1,controller.deadlineAt-Date.now()));watchdog.unref?.()}
    for(let index=0;index<Math.min(workerCount,chunks.length);index++){
      const worker=new Worker(new URL("./simulation-batch-worker.js",import.meta.url),{workerData:{pooled:true,state:input.state,candidates,userSlot:input.userSlot,seed:input.seed||2026}});workers.add(worker);controller?.workers.add(worker);
      worker.on("message",message=>{const taskId=Number(message.taskId),chunk=chunks[taskId];if(message.kind==="progress"){if(chunk){progressByShard.set(chunk.scenarioOffset,Math.min(chunk.iterations,Number(message.completed)||0));emitProgress()}return}if(!message.ok)return finish(new Error(message.error));if(!chunk)return finish(new Error("simulation worker returned an unknown chunk"));parts[taskId]=message;progressByShard.set(chunk.scenarioOffset,chunk.iterations);completedChunks++;emitProgress();if(completedChunks===chunks.length)finish();else assign(worker)});
      worker.once("error",error=>finish(error));worker.once("exit",code=>{if(!settled)finish(new Error(`simulation batch worker exited (${code})`))});assign(worker)
    }
  })
}
async function workerEvaluation(input,iterations,controller,onProgress=null){
  const currentSlot=snakeSlot(input.state.picks.length+1,input.state.settings.teams),items=Array.isArray(input.precomputedRecommendations)&&input.precomputedRecommendations.length?input.precomputedRecommendations:recommend({...input,limit:Number(input.limit)||8}),candidates=[null,...items.map(item=>item.player)],workerCount=Math.min(chooseWorkerConcurrency(),iterations),cacheKeys=candidates.map(candidate=>simulationKey(input,iterations,candidate)),cached=cacheKeys.map(key=>candidateSimulationCache.get(key));
  let simulations=cached;
  if(cached.some(value=>!value)){
    // Over-partition the deterministic scenario bank so a few slow workers do
    // not hold the final 1-2k scenarios hostage. The persistent request pool
    // hands the next short chunk to whichever worker slot becomes free first.
    const chunkCount=Math.min(iterations,Math.max(1,workerCount*3)),base=Math.floor(iterations/chunkCount),extra=iterations%chunkCount,chunks=[];let scenarioOffset=0;
    for(let index=0;index<chunkCount;index++){const count=base+(index<extra?1:0);if(count>0){chunks.push({scenarioOffset,iterations:count});scenarioOffset+=count}}
    const parts=await workerSimulationChunkPool({input,candidates,chunks,workerCount,controller,onProgress});
    parts.sort((a,b)=>a.scenarioOffset-b.scenarioOffset);
    simulations=candidates.map((candidate,candidateIndex)=>{const scenarioWins=new Uint8Array(iterations),planScenarioWins=new Uint8Array(iterations),scenarioSelected=new Uint8Array(iterations);let offset=0;for(const part of parts){const row=part.rows[candidateIndex];scenarioWins.set(row.scenarioWins,offset);planScenarioWins.set(row.planScenarioWins,offset);scenarioSelected.set(row.scenarioSelected,offset);offset+=row.scenarioWins.length}let selected=0,wins=0,planWins=0;for(let index=0;index<iterations;index++){selected+=scenarioSelected[index];wins+=scenarioWins[index];planWins+=planScenarioWins[index]}const sampleIterations=candidate?selected:iterations,sampleWins=candidate?wins:planWins,rawProbability=sampleIterations?sampleWins/sampleIterations:1/input.state.settings.teams,calibrated=calibrateTitleProbability({wins:sampleWins,iterations:Math.max(1,sampleIterations),teams:input.state.settings.teams}),planRawProbability=planWins/iterations,planCalibrated=calibrateTitleProbability({wins:planWins,iterations,teams:input.state.settings.teams}),simulation={...calibrated,rawProbability,conditionalRawProbability:rawProbability,conditionalChampionshipProbability:calibrated.championshipProbability,planRawProbability,planChampionshipProbability:planCalibrated.championshipProbability,conditional:Boolean(candidate),candidateSelectionProbability:candidate?selected/iterations:null,effectiveCandidateIterations:sampleIterations,iterations,seed:input.seed||2026,simulationModel:"legacy",scenarioBankId:`crn-v1:${input.seed||2026}:${iterations}`};Object.defineProperties(simulation,{scenarioWins:{value:scenarioWins,enumerable:false},planScenarioWins:{value:planScenarioWins,enumerable:false},scenarioSelected:{value:scenarioSelected,enumerable:false}});setBounded(candidateSimulationCache,cacheKeys[candidateIndex],simulation,MAX_SIMULATION_CACHE);return simulation})
  }
  const teamSimulation=simulations[0],simulationByPlayerId=new Map(items.map((item,index)=>[item.player.id,simulations[index+1]]));
  const evaluated=items.map(item=>{const simulation=simulationByPlayerId.get(item.player.id),paired=pairedDifference(simulation,teamSimulation);if(paired)Object.assign(simulation,{pairedDifference:paired.rawDifference,pairedStandardError:paired.standardError,pairedInterval:paired.interval,pairedScenarioBankId:paired.scenarioBankId});return{...item,waitingForUserPick:currentSlot!==input.userSlot,teamSimulation,simulation}});
  return rankEvaluatedRecommendations(evaluated,{strategy:input.strategy||"balanced"});
}
const projectedFinalFromSimulation=simulation=>{const projected=Number(simulation?.projectedFinalChampionshipProbability);if(Number.isFinite(projected))return projected;const raw=Number(simulation?.rawProbability),priorStrength=Number(simulation?.priorStrength),priorProbability=Number(simulation?.priorProbability),targetIterations=10000;return Number.isFinite(raw)&&Number.isFinite(priorStrength)&&Number.isFinite(priorProbability)?Math.max(0,Math.min(1,(raw*targetIterations+priorStrength*priorProbability)/(targetIterations+priorStrength))):Number(simulation?.championshipProbability||0)};
function evidenceDisplay(items,readiness){const byId=new Map(items.map(item=>[item.player.id,item])),result=[];for(const ids of readiness.displayGroups){const group=ids.map(id=>byId.get(id)).filter(Boolean),displayRank=result.length+1,calibrated=titleTenths(group.reduce((sum,item)=>sum+Number(item.simulation.championshipProbability),0)/Math.max(1,group.length))/1000,projectedFinal=titleTenths(group.reduce((sum,item)=>sum+projectedFinalFromSimulation(item.simulation),0)/Math.max(1,group.length))/1000;for(const item of group){const teamProjectedFinal=titleTenths(projectedFinalFromSimulation(item.teamSimulation))/1000;result.push({...item,teamSimulation:{...item.teamSimulation,calibratedChampionshipProbability:Number(item.teamSimulation?.championshipProbability||0),projectedFinalChampionshipProbability:teamProjectedFinal,championshipProbability:teamProjectedFinal,displayChampionshipProbability:teamProjectedFinal},displayRank,statisticalTie:group.length>1,simulation:{...item.simulation,calibratedChampionshipProbability:calibrated,projectedFinalChampionshipProbability:projectedFinal,championshipProbability:projectedFinal,displayChampionshipProbability:projectedFinal,displayTitleTenths:titleTenths(projectedFinal),evidenceStatus:group.length>1?"indistinguishable":"supported"}})}}return result}
const terminalEvaluationStatus=status=>["complete","deadline_fallback","worker_fallback","cancelled"].includes(String(status||""));
const evaluationIdForKey=key=>crypto.createHash("sha256").update(key).digest("hex").slice(0,24);
function evaluationIdentity(input,{calibrated,quickIterations,targetIterations,deadlineEnabled}){return JSON.stringify({state:stateFingerprint(input.state),draftRunId:input.state.draftRunId||"",userSlot:Number(input.userSlot),strategy:input.strategy||"balanced",sourceProfile:input.sourceProfile||"projectionLed",customWeights:input.customWeights||null,positions:Array.isArray(input.positions)?[...input.positions].sort():null,calibrated,quickIterations,targetIterations,limit:Math.max(1,Number(input.limit)||8),seed:Number(input.seed)||2026,deadlineEnabled,consumer:input.consumer==="shared"?"shared":"gui"})}
function refinementWorkIdentity(input,{targetIterations}){return JSON.stringify({state:stateFingerprint(input.state),draftRunId:input.state.draftRunId||"",userSlot:Number(input.userSlot),strategy:input.strategy||"balanced",sourceProfile:input.sourceProfile||"projectionLed",customWeights:input.customWeights||null,positions:Array.isArray(input.positions)?[...input.positions].sort():null,targetIterations,limit:Math.max(1,Number(input.limit)||8),seed:Number(input.seed)||2026})}
function setEvaluation(key,evaluationId,value){setBounded(evaluationCache,key,{at:Date.now(),evaluationId,value},MAX_EVALUATION_CACHE);evaluationKeyById.set(evaluationId,key);for(const[id,mappedKey]of evaluationKeyById)if(!evaluationCache.has(mappedKey))evaluationKeyById.delete(id)}
function evaluationById(evaluationId){const key=evaluationKeyById.get(evaluationId),entry=key&&evaluationCache.get(key);if(!entry||Date.now()-entry.at>EVALUATION_RETENTION_MS){if(key)evaluationKeyById.delete(evaluationId);return null}return{key,entry}}
const evaluationEnvelope=(evaluationId,value,extra={})=>({...value,...extra,evaluationId,clientBuildId:CURRENT_CLIENT_BUILD_ID,status:value.status||(value.simulationStatus==="refined"?"complete":"refining")});
function cancelRefinement(entry,{publishCancelled=false}={}){if(!entry)return;entry.controller.cancelled=true;clearTimeout(entry.controller.deadlineTimer);entry.lease?.release();if(!entry.lease){for(const worker of entry.controller.workers)worker.terminate();entry.controller.workers.clear()}if(publishCancelled&&entry.key&&entry.evaluationId){const current=evaluationCache.get(entry.key)?.value,cancelledAt=Date.now();if(current)setEvaluation(entry.key,entry.evaluationId,{...current,status:"cancelled",simulationStatus:"refined",refinementOutcome:"cancelled",cancelledAt,refinementMs:Math.max(0,cancelledAt-Number(current.startedAt||cancelledAt)),generatedAt:cancelledAt})}}
const refinementScope=input=>`${input.installationId||"anonymous"}:gui:${input.state.platform}:${input.state.draftId}:${input.state.draftRunId||""}:${input.userSlot}`;
function cancelActiveRefinement(input){const scope=refinementScope(input),previous=activeRefinements.get(scope);if(!previous)return;cancelRefinement(previous,{publishCancelled:true});if(refinementJobs.get(previous.key)===previous)refinementJobs.delete(previous.key);if(activeRefinements.get(scope)===previous)activeRefinements.delete(scope)}
function refinementPriority(input){const onClock=snakeSlot(input.state.picks.length+1,input.state.settings.teams)===Number(input.userSlot);return input.clockPriority===true?30:onClock?20:10}
function queueRefinement(key,evaluationId,input,calibrated,iterations,fallbackRanked,fallbackIterations,{deadlineBudgetMs=refinementDeadlineMs,startedAt=Date.now(),deadlineAt=null,workKey=key}={}){
  const existing=refinementJobs.get(key);if(existing&&!existing.controller.cancelled)return;if(existing)refinementJobs.delete(key);
  const scope=refinementScope(input),previous=activeRefinements.get(scope);
  if(previous&&previous.key!==key){cancelRefinement(previous,{publishCancelled:true});if(refinementJobs.get(previous.key)===previous)refinementJobs.delete(previous.key)}
  const deadlineEnabled=deadlineBudgetMs!==false,budgetMs=deadlineEnabled?Math.min(refinementDeadlineMs,Math.max(10,Number(deadlineBudgetMs)||refinementDeadlineMs)):null,controller={workers:new Set(),cancelled:false,settled:false,timedOut:false,startedAt:performance.now(),startedAtEpoch:startedAt,deadlineAt:deadlineEnabled?(deadlineAt||Date.now()+budgetMs):null,deadlineTimer:null,decorate:items=>calibrated?items:items.map(item=>({...item,confidenceBand:"experimental"}))};
  const publish=(ranked,count,status,extra={})=>{const{force=false,...metadata}=extra;if(controller.cancelled&&!force)return null;const readiness=assessRankingReadiness(ranked,{iterations:count,targetIterations:iterations,stageIterations:count}),current=evaluationCache.get(key)?.value||{},recommendations=evidenceDisplay(ranked,readiness),value={...current,...metadata,generatedAt:Date.now(),calibrated,status,simulationStatus:terminalEvaluationStatus(status)?"refined":"refining",iterations:count,targetIterations:iterations,startedAt:controller.startedAtEpoch,deadlineAt:controller.deadlineAt,refinementMs:Math.round(performance.now()-controller.startedAt),workerCount:chooseWorkerConcurrency(),readiness,recommendations:controller.decorate(recommendations)};setEvaluation(key,evaluationId,value);return readiness};
  const entry={key,evaluationId,scope,workKey,controller,job:null,lease:null};
  entry.lease=sharedRefinementPool.acquire(workKey,()=>{const sharedController={workers:new Set(),cancelled:false,deadlineAt:null},sharedInput={...input,consumer:"shared",sharedWorkKey:workKey},onClock=snakeSlot(input.state.picks.length+1,input.state.settings.teams)===Number(input.userSlot),scheduled=fullRefinementScheduler.schedule(workKey,()=>workerEvaluation(sharedInput,iterations,sharedController),{priority:refinementPriority(input),preemptLowerPriority:input.clockPriority===true&&onClock,metadata:{workId:crypto.createHash("sha1").update(workKey).digest("hex").slice(0,12),consumer:input.consumer,pickCount:input.state.picks.length,onClock,createdAt:Date.now()},onCancel:()=>{sharedController.cancelled=true;for(const worker of sharedController.workers)worker.terminate();sharedController.workers.clear()}});return{promise:scheduled.promise,controller:sharedController,cancel:scheduled.cancel}});
  controller.sharedController=entry.lease.operation.controller;
  if(deadlineEnabled){controller.deadlineTimer=setTimeout(()=>{if(controller.cancelled||controller.settled)return;controller.timedOut=true;controller.settled=true;publish(fallbackRanked,fallbackIterations,"deadline_fallback",{refinementOutcome:"deadline_fallback",refinementDeadlineMs});cancelRefinement(entry)},budgetMs);controller.deadlineTimer.unref?.()}
  entry.job=entry.lease.promise.then(ranked=>{if(controller.cancelled||controller.settled)return;controller.settled=true;clearTimeout(controller.deadlineTimer);publish(ranked,iterations,"complete",{refinementOutcome:"complete"})}).catch(error=>{if(controller.cancelled||controller.timedOut)return;controller.settled=true;clearTimeout(controller.deadlineTimer);const deadlineFailure=error?.code==="REFINEMENT_DEADLINE";publish(fallbackRanked,fallbackIterations,deadlineFailure?"deadline_fallback":"worker_fallback",{refinementOutcome:deadlineFailure?"deadline_fallback":"worker_fallback",refinementError:String(error?.message||error)})}).finally(()=>{entry.lease.release();clearTimeout(controller.deadlineTimer);if(refinementJobs.get(key)===entry)refinementJobs.delete(key);if(activeRefinements.get(scope)===entry)activeRefinements.delete(scope)});
  activeRefinements.set(scope,entry);refinementJobs.set(key,entry)
}
const activeWorkerCount=()=>new Set([...activeRefinements.values()].flatMap(entry=>[...(entry.controller.sharedController?.workers||entry.controller.workers)])).size;
const refinementStats=()=>({jobs:refinementJobs.size,activeWorkers:activeWorkerCount(),sharedWork:sharedRefinementPool.stats(),fullRefinementScheduler:fullRefinementScheduler.stats(),hasActiveRefinement:activeRefinements.size>0,deadlineMs:refinementDeadlineMs});
function evaluationDiagnostics(){const now=Date.now(),activeByKey=new Map([...activeRefinements.values()].map(entry=>[entry.key,entry])),scheduler=fullRefinementScheduler.stats(),recent=[...evaluationCache.entries()].filter(([,entry])=>now-entry.at<=EVALUATION_RETENTION_MS).sort((a,b)=>b[1].at-a[1].at).slice(0,MAX_DIAGNOSTIC_EVALUATIONS).map(([key,entry])=>{const value=entry.value||{},active=activeByKey.get(key),startedAt=Number(value.startedAt||entry.at),terminal=terminalEvaluationStatus(value.status);return{evaluationId:entry.evaluationId,status:value.status||"unknown",terminal,consumer:value.consumer||"unknown",elapsedMs:terminal&&Number.isFinite(value.refinementMs)?value.refinementMs:Math.max(0,now-startedAt),iterations:Number(value.iterations)||0,targetIterations:Number(value.targetIterations)||0,cancelledAt:Number(value.cancelledAt)||null,workState:active?.workKey?fullRefinementScheduler.stateFor(active.workKey):null,activeWorkers:active?.controller?.sharedController?.workers?.size||active?.controller?.workers?.size||0}}),statusCounts={};for(const item of recent)statusCounts[item.status]=(statusCounts[item.status]||0)+1;return{recentEvaluations:recent,statusCounts,rateLimits:{...rateLimitStats,evaluationStatusCapacityPerMinute:EVALUATION_STATUS_RATE_LIMIT},pressure:{activeEvaluations:activeRefinements.size,queuedEvaluations:refinementJobs.size,activeWorkers:activeWorkerCount(),candidateSimulationsInFlight:candidateSimulationInflight.size,fullRefinementActive:scheduler.activeCount,fullRefinementQueued:scheduler.queuedCount,fullRefinement:scheduler,...sharedRefinementPool.stats()}}}
const setRefinementDeadlineForTests=value=>{refinementDeadlineMs=value==null?configuredRefinementDeadline():Math.min(MAX_REFINEMENT_DEADLINE_MS,Math.max(10,Number(value)||MAX_REFINEMENT_DEADLINE_MS))};
const server=http.createServer(async(req,res)=>{
  if(req.method==="OPTIONS"){res.writeHead(204,headers);return res.end()}const evaluationStatusId=req.method==="GET"&&req.url?.startsWith("/v1/evaluate/")?decodeURIComponent(req.url.slice("/v1/evaluate/".length).split("?")[0]):null;if(evaluationStatusId!==null){if(evaluationStatusLimited(req,evaluationStatusId))return send(res,429,{error:"evaluation status rate limit exceeded"})}else if(limited(req,req.url==="/v1/evaluate"?180:120))return send(res,429,{error:"rate limit exceeded"});
  try{
    if(req.url==="/health"){const active=[...activeRefinements.values()],oldestStartedAt=active.length?Math.min(...active.map(entry=>Number(entry.controller.startedAtEpoch||Date.now()))):null;return send(res,200,{ok:true,version:"0.4.0",clientBuildId:CURRENT_CLIENT_BUILD_ID,simulationModelVersion:SIMULATION_MODEL_VERSION,sourceMtimeMs:SERVER_SOURCE_MTIME_MS,refinementDeadlineMs,activeEvaluationCount:active.length,oldestEvaluationAgeMs:oldestStartedAt==null?0:Math.max(0,Date.now()-oldestStartedAt),lastDeepEvaluation,projectionSnapshots:projectionSnapshotDiagnostics(),distributionShadow:distributionShadowTelemetry.diagnostics(),evaluationDiagnostics:evaluationDiagnostics()})}
    if(req.url==="/v1/catalog"&&req.method==="GET"){if(!baselineCatalog)return send(res,503,{error:"projection baseline has not been built"});return send(res,200,{...baselineCatalog,...(playerDistributionCalibration?{distributionCalibration:playerDistributionCalibration}:{})})}
    if(req.url==="/v1/player-board"&&req.method==="POST"){const input=await json(req);return send(res,200,{generatedAt:Date.now(),candidates:buildCandidateBoard(input),clientBuildId:CURRENT_CLIENT_BUILD_ID})}
    if(req.url==="/v1/draft-report"&&req.method==="POST"){const input=await json(req),report=buildDraftReport({state:input.state,userSlot:Number(input.userSlot),iterations:Math.min(20000,Math.max(1000,Number(input.iterations)||10000))}),reportId=crypto.randomUUID();reportStore.set(reportId,report);return send(res,201,{reportId,url:`http://localhost:${PORT}/reports/${reportId}`,report})}
    if(req.url?.startsWith("/v1/draft-report/")&&req.method==="GET"){const entry=reportStore.get(decodeURIComponent(req.url.slice("/v1/draft-report/".length)));return entry?send(res,200,entry.report):send(res,404,{error:"draft report not found"})}
    if(req.url?.startsWith("/reports/")&&req.method==="GET"){const reportId=decodeURIComponent(req.url.slice("/reports/".length)),entry=reportStore.get(reportId);if(!entry)return send(res,404,{error:"draft report not found"});res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});return res.end(reportPage(reportId))}
    if(req.url?.startsWith("/v1/projections/fantasypros")&&req.method==="GET"){const url=new URL(req.url,"http://localhost"),season=Number(url.searchParams.get("season")||new Date().getFullYear()),scoring=url.searchParams.get("scoring")||"PPR";return send(res,200,await currentFantasyPros({season,scoring,apiKey:req.headers["x-fantasypros-key"]||process.env.FANTASYPROS_API_KEY}))}
    if(req.url?.startsWith("/v1/projections/sleeper")&&req.method==="GET"){const url=new URL(req.url,"http://localhost"),season=Number(url.searchParams.get("season")||new Date().getFullYear()),scoring=url.searchParams.get("scoring")||"PPR";return send(res,200,await refreshSleeperProjections({season,scoring}))}
    if(req.url==="/v1/calibrate-projection"&&req.method==="POST"){const input=await json(req,100000),players=Array.isArray(input.players)?input.players:[input];return send(res,200,{generatedAt:calibrationReport.generatedAt,players:players.map(player=>projectedOutcome(calibrationReport,player))})}
    if(req.url==="/v1/evaluate/deep"&&req.method==="POST"){
      const startedAt=Date.now(),input=await json(req),iterations=Math.min(Math.max(1000,Number(input.iterations)||10000),20000),controller={workers:new Set(),cancelled:false,deadlineAt:null},workerCount=Math.min(chooseWorkerConcurrency(),iterations),streamProgress=String(req.headers.accept||"").includes("application/x-ndjson"),requestBytes=Buffer.byteLength(JSON.stringify(input));let lastProgressEmitAt=0;
      const diagnostic={startedAt,requestBytes,sourceHeaderBytes:Number(req.headers["content-length"])||null,players:input.state?.players?.length||0,picks:input.state?.picks?.length||0,candidates:input.precomputedRecommendations?.length||0,iterations,workerCount,firstProgressMs:null,lastProgressMs:null,completed:0,status:"running"};lastDeepEvaluation=diagnostic;captureLiveDeepReplay(input,requestBytes);
      if(!streamProgress){const recommendations=await workerEvaluation({...input,consumer:"accelerator"},iterations,controller),serverElapsedMs=Date.now()-startedAt;diagnostic.status="complete";diagnostic.completed=iterations;diagnostic.elapsedMs=serverElapsedMs;return send(res,200,{generatedAt:Date.now(),deep:true,iterations,workerCount,serverElapsedMs,recommendations})}
      res.writeHead(200,{...headers,"content-type":"application/x-ndjson; charset=utf-8","cache-control":"no-store"});
      res.on("close",()=>{if(res.writableEnded)return;diagnostic.status="cancelled";diagnostic.elapsedMs=Date.now()-startedAt;controller.cancelled=true;for(const worker of controller.workers)worker.terminate();controller.workers.clear()});
      try{
        const recommendations=await workerEvaluation({...input,consumer:"accelerator"},iterations,controller,progress=>{const now=Date.now(),completed=Number(progress.completed)||0;diagnostic.firstProgressMs??=now-startedAt;diagnostic.lastProgressMs=now-startedAt;diagnostic.completed=completed;if(!res.destroyed&&(completed>=iterations||now-lastProgressEmitAt>=100)){lastProgressEmitAt=now;res.write(`${JSON.stringify({type:"progress",...progress})}\n`)}});
        diagnostic.status="complete";diagnostic.completed=iterations;diagnostic.elapsedMs=Date.now()-startedAt;if(!res.destroyed){res.write(`${JSON.stringify({type:"result",data:{generatedAt:Date.now(),deep:true,iterations,workerCount,serverElapsedMs:diagnostic.elapsedMs,recommendations}})}\n`);res.end()}
      }catch(error){diagnostic.status=controller.cancelled?"cancelled":"error";diagnostic.error=String(error?.message||error);diagnostic.elapsedMs=Date.now()-startedAt;if(!res.destroyed){res.write(`${JSON.stringify({type:"error",error:error.message})}\n`);res.end()}}
      return
    }
    if(req.url==="/v1/auth/register"&&req.method==="POST")return send(res,201,auth.register(...((({email,password})=>[email,password])(await json(req,10000)))));
    if(req.url==="/v1/auth/login"&&req.method==="POST")return send(res,200,auth.login(...((({email,password})=>[email,password])(await json(req,10000)))));
    if(req.url==="/v1/auth/logout"&&req.method==="POST"){auth.logout(bearer(req));return send(res,204,{})}
    const user=auth.userForToken(bearer(req));
    if(req.url==="/v1/me"&&req.method==="GET")return user?send(res,200,user):send(res,401,{error:"authentication required"});
    if(req.url==="/v1/preferences"&&req.method==="PUT")return user?send(res,200,auth.preferences(user.id,await json(req,50000))):send(res,401,{error:"authentication required"});
    if(req.url==="/v1/account"&&req.method==="DELETE"){if(!user)return send(res,401,{error:"authentication required"});auth.deleteUser(user.id);return send(res,204,{})}
    if(evaluationStatusId!==null){const evaluationId=evaluationStatusId,found=evaluationById(evaluationId);return found?send(res,200,evaluationEnvelope(evaluationId,found.entry.value,{cached:true})):send(res,404,{error:"evaluation not found",evaluationId,clientBuildId:CURRENT_CLIENT_BUILD_ID})}
    if(req.url==="/v1/evaluate"&&req.method==="POST"){
      const input=await json(req);if(input.clientBuildId!==undefined&&String(input.clientBuildId)!==CURRENT_CLIENT_BUILD_ID)return send(res,409,{error:"Draft Goblin build mismatch. Reload the extension and restart the local service.",clientBuildId:CURRENT_CLIENT_BUILD_ID});
      input.installationId=String(req.headers["x-installation-id"]||"anonymous");input.consumer="gui";capturePlatformSnapshot(input.state);if(input.clockPriority===true)cancelActiveRefinement(input);
      const requestStarted=performance.now(),startedAt=Date.now(),calibrated=baselineQuality==="calibrated",deadlineEnabled=input.refinementDeadline!==false,quickIterations=calibrated?Math.min(input.iterations||300,300):Math.min(input.iterations||120,120),targetIterations=Math.min(10000,Math.max(quickIterations,Number(input.refineIterations)||quickIterations)),identityOptions={calibrated,quickIterations,targetIterations,deadlineEnabled},key=evaluationIdentity(input,identityOptions),workKey=refinementWorkIdentity(input,{targetIterations}),evaluationId=evaluationIdForKey(key),cached=evaluationCache.get(key);
      if((cached?.value?.status==="refining"&&!refinementJobs.has(key))||cached?.value?.status==="cancelled")evaluationCache.delete(key);else if(cached&&(terminalEvaluationStatus(cached.value.status)||Date.now()-cached.at<EVALUATION_RETENTION_MS))return send(res,200,evaluationEnvelope(cached.evaluationId||evaluationId,cached.value,{cached:true,responseMs:Math.round(performance.now()-requestStarted)}));
      const refining=targetIterations>quickIterations,result=evaluateDraft({...input,includeSimulation:true,iterations:quickIterations}),quickReadiness=assessRankingReadiness(result,{iterations:quickIterations,targetIterations,stageIterations:quickIterations}),displayed=evidenceDisplay(result,quickReadiness),recommendations=calibrated?displayed:displayed.map(item=>({...item,confidenceBand:"experimental"})),deadlineAt=deadlineEnabled?startedAt+refinementDeadlineMs:null,value={generatedAt:Date.now(),calibrated,consumer:input.consumer,status:refining?"refining":"complete",simulationStatus:refining?"refining":"quick",iterations:quickIterations,targetIterations,startedAt,deadlineAt,refinementDeadlineEnabled:deadlineEnabled,responseMs:Math.round(performance.now()-requestStarted),readiness:quickReadiness,recommendations};scheduleDistributionShadow({state:input.state,evaluate:evaluateDraft,options:{...input,includeSimulation:true,iterations:Math.min(200,quickIterations)},telemetry:distributionShadowTelemetry,metadata:{draftId:input.state.draftId,pickCount:input.state.picks.length,seed:Number(input.seed)||2026}});
      setEvaluation(key,evaluationId,value);if(refining)queueRefinement(key,evaluationId,input,calibrated,targetIterations,result,quickIterations,{deadlineBudgetMs:deadlineEnabled?Math.max(10,deadlineAt-Date.now()):false,startedAt,deadlineAt,workKey});return send(res,200,evaluationEnvelope(evaluationId,value))
    }
    return send(res,404,{error:"not found"});
  }catch(error){return send(res,error?.code==="PAYLOAD_TOO_LARGE"?413:400,{error:error.message,code:error?.code||"BAD_REQUEST"})}
});
if(process.argv[1]&&import.meta.url.endsWith(process.argv[1].replaceAll("\\","/")))server.listen(PORT,()=>console.log(`Draft Goblin API on http://localhost:${PORT}`));
export{server,auth,reportStore,refinementStats,setRefinementDeadlineForTests,workerEvaluation};
