import {SIMULATION_MODEL_VERSION} from "../core/simulate.js";

const safe = value => JSON.stringify(String(value));

export function reportPage(reportId) {
  return `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Draft Goblin Report</title><style>
:root{color-scheme:dark;--bg:#07110e;--panel:#11201a;--line:#294638;--text:#f3f8f5;--muted:#9bb3a8;--accent:#65e6a2}*{box-sizing:border-box}body{margin:0;background:linear-gradient(145deg,#10231b,var(--bg));color:var(--text);font:15px system-ui,sans-serif}main{max-width:1100px;margin:auto;padding:28px}.top{display:grid;grid-template-columns:220px 1fr;gap:18px}.card{background:#0f1c17;border:1px solid var(--line);border-radius:16px;padding:20px;margin-bottom:18px}.warning{border-color:#d69a36;background:#2b2111;color:#ffe2a8}.top .card{margin-bottom:0}.grade span,.grade strong{display:block}.grade strong{font-size:54px;color:var(--accent);line-height:1.05;margin:8px 0}h1,h2{margin-top:0}.muted{color:var(--muted)}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid var(--line)}.bar{height:9px;background:#1f342b;border-radius:9px;overflow:hidden}.bar i{display:block;height:100%;background:var(--accent)}.finish{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}.finish div{padding:10px;border:1px solid var(--line);border-radius:10px}.finish strong,.finish span{display:block}.finish span{color:var(--muted);font-size:12px}@media(max-width:700px){.top{grid-template-columns:1fr}.finish{grid-template-columns:repeat(2,minmax(0,1fr))}main{padding:14px}.card{overflow-x:auto}}
</style></head><body><main id="app"><p>Loading draft report...</p></main><script>
const id=${safe(reportId)},currentModel=${safe(SIMULATION_MODEL_VERSION)},pct=n=>(n*100).toFixed(3)+'%',pp=n=>(n>=0?'+':'')+(n*100).toFixed(2)+' pp',esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
fetch('/v1/draft-report/'+encodeURIComponent(id)).then(r=>r.json()).then(report=>{
  const user=report.userTeam,max=Math.max(...report.teamReports.map(t=>t.points)),fair=1/report.teams,leaderTitle=Math.max(...report.teamReports.map(team=>team.finishProbabilities[0])),modelStale=report.simulationModelVersion!==currentModel;
  document.getElementById('app').innerHTML='<h1>Draft Goblin report</h1>'+(modelStale?'<section class="card warning"><strong>Stale simulation model</strong><br>This report used '+esc(report.simulationModelVersion||'an unversioned legacy model')+', while the current model is '+esc(currentModel)+'. Regenerate it before relying on its title odds, rank, grade, or hindsight.</section>':'')+
    '<div class="top"><section class="card grade"><span class="muted">'+(modelStale?'Stale legacy-model grade':'Overall draft grade')+'</span><strong>'+report.grade.letter+'</strong><h2>'+report.grade.score+' / 100</h2><span class="muted">'+(modelStale?'Not comparable to current-model grades':'Title odds only: room-relative rank plus lift over equal-team odds')+'</span></section><section class="card"><span class="muted">Championship outlook</span><h2>'+pct(user.finishProbabilities[0])+' title chance</h2><p>Title-odds rank <strong>#'+user.titleRank+'</strong> of '+report.teams+' | projected weekly rank <strong>#'+user.weeklyRank+'</strong></p><p class="muted">'+Number(user.pointsExact??user.points).toFixed(3)+' projected points/week</p><div class="bar"><i style="width:'+(user.finishProbabilities[0]/leaderTitle*100)+'%"></i></div></section></div>'+
    '<section class="card"><h2>How to read this result</h2><div class="finish"><div><strong>#'+user.weeklyRank+' of '+report.teams+'</strong><span>Projected weekly scoring</span></div><div><strong>#'+user.titleRank+' of '+report.teams+'</strong><span>Title-odds rank</span></div><div><strong>'+pp(user.finishProbabilities[0]-fair)+'</strong><span>Versus equal-team title odds</span></div><div><strong>'+pp(user.finishProbabilities[0]-leaderTitle)+'</strong><span>Gap to title-odds leader</span></div></div><p class="muted">Small differences in simulated title odds can change ordinal rank without meaningfully changing roster quality.</p></section>'+
    '<section class="card"><h2>Your draft</h2><table><thead><tr><th>Round</th><th>Overall pick</th><th>Player</th><th>Position</th><th>NFL team</th></tr></thead><tbody>'+user.draft.map(p=>'<tr><td>'+p.round+'</td><td>#'+p.pickNo+'</td><td><strong>'+esc(p.name)+'</strong></td><td>'+esc(p.position)+'</td><td>'+esc(p.team)+'</td></tr>').join('')+'</tbody></table></section>'+
    '<section class="card"><h2>Championship odds ranking</h2><table><thead><tr><th>Title rank</th><th>Team</th><th>Title chance</th><th>Projected points/week</th></tr></thead><tbody>'+[...report.teamReports].sort((a,b)=>a.titleRank-b.titleRank).map(t=>'<tr><td>#'+t.titleRank+'</td><td>'+(t.slot===report.userSlot?'<strong>Your team</strong>':'Team '+t.slot)+'</td><td><strong>'+pct(t.finishProbabilities[0])+'</strong></td><td>'+Number(t.pointsExact??t.points).toFixed(3)+'</td></tr>').join('')+'</tbody></table><p class="muted">'+report.iterations.toLocaleString()+' simulations. '+report.method+'</p></section>';
});
function ordinal(n){return n%100>=11&&n%100<=13?'th':n%10===1?'st':n%10===2?'nd':n%10===3?'rd':'th'}
function signed(n){return(n>=0?'+':'')+Number(n).toFixed(3)}
</script></body></html>`;
}
