(async function espnAdapter() {
  const clean=value=>String(value||"").trim();
  const usablePlayerName=value=>{const name=clean(value);return name&&!/^(?:draft|queue|add|remove|watch|claim|move)$/i.test(name)?name:""};
  const contiguousTeamOrder=values=>{const ordered=values.map(Number);if(ordered.some(id=>!Number.isInteger(id)||id<=0))return[];const unique=[...new Set(ordered)];return unique.length>=4&&unique.length===ordered.length?unique:[]};
  const teamOrderFromSelects=(selects,teamId)=>{let best=[],bestVerified=false;for(const select of selects||[]){const optionText=(select.options||[]).map(option=>clean(option.text)),testId=clean(select.testId);if(/(?:pick)?time|clock/i.test(testId)||optionText.length&&optionText.every(text=>/\b(?:seconds?|minutes?|hours?)\b/i.test(text)))continue;const order=contiguousTeamOrder((select.options||[]).map(option=>option.value)),verified=Number.isInteger(Number(teamId))&&Number(select.selectedValue)===Number(teamId)&&order.includes(Number(teamId));if(order.length&&(verified&&!bestVerified||verified===bestVerified&&order.length>best.length)){best=order;bestVerified=verified}}return best};
  const slotForTeam=(order,teamId)=>{const index=order.indexOf(Number(teamId));return index>=0?index+1:null};
  const receptionValue=text=>/\bhalf(?:[-\s]?point)?[-\s]?ppr\b|\b0\.5\s*ppr\b|\bhalf[-\s]?point(?:s)? per reception\b/i.test(clean(text))?.5:/\bppr\b|\bpoint(?:s)? per reception\b/i.test(clean(text))?1:0;
  const currentPickFromTexts=texts=>{for(const value of texts||[]){const match=clean(value).match(/^on the clock:\s*pick\s*(\d+)(?!\d)/i),pickNo=Number(match?.[1]);if(Number.isInteger(pickNo)&&pickNo>0)return pickNo}return null};
  const userSlotFromClockTexts=(texts,currentPick,teams)=>{const activePick=Number(currentPick),teamCount=Number(teams);if(!Number.isInteger(activePick)||activePick<1||!Number.isInteger(teamCount)||teamCount<2)return null;for(const value of texts||[]){const match=clean(value).match(/you(?:'|’|\u2019)?re on the clock in:\s*(\d+)\s*pick(?:s)?\b/i),picksAway=Number(match?.[1]),targetPick=activePick+picksAway;if(Number.isInteger(picksAway)&&picksAway>=0&&Number.isInteger(targetPick)&&targetPick>0)return snakeSlot(targetPick,teamCount)}return null};
  const visibleOverallRank=(...texts)=>{for(const text of texts){const match=clean(text).match(/^(\d{1,3})(?:\s|$)/),rank=Number(match?.[1]);if(Number.isInteger(rank)&&rank>0)return rank}return 0};
  const pickNumberFromRow=root=>{const explicit=Number(root?.getAttribute?.("data-pick")||root?.getAttribute?.("data-pick-number")),firstCell=clean(root?.querySelector?.("td,[role=gridcell]")?.textContent),cellPick=/^\d+$/.test(firstCell)?Number(firstCell):0;return Number.isInteger(explicit)&&explicit>0?explicit:Number.isInteger(cellPick)&&cellPick>0?cellPick:0};
  const snakeSlot=(pickNo,teams)=>{const round=Math.floor((pickNo-1)/teams)+1,within=(pickNo-1)%teams+1;return round%2?within:teams+1-within};
  const normalizePicks=(rawPicks,teams)=>{const byNumber=new Map();for(const raw of rawPicks){const pickNo=Number(raw.pickNo),playerId=clean(raw.playerId),slot=Number(raw.slot)||snakeSlot(pickNo,teams);if(!Number.isInteger(pickNo)||pickNo<1||!playerId)continue;const pick={pickNo,playerId,slot,name:clean(raw.name)},prior=byNumber.get(pickNo);if(prior&&(prior.playerId!==pick.playerId||prior.slot!==pick.slot))return{error:`ESPN pick ${pickNo} was reported with conflicting players.`,picks:[]};if(!prior)byNumber.set(pickNo,pick)}const picks=[...byNumber.values()].sort((a,b)=>a.pickNo-b.pickNo);if(picks.some((pick,index)=>pick.pickNo!==index+1))return{error:"ESPN pick history is not contiguous yet.",picks:[]};return{error:"",picks}};
  const completedPicksBeforeClock=(rawPicks,currentPick,history,conflicts)=>{
    const boundary=Number(currentPick);if(!Number.isInteger(boundary)||boundary<1)return rawPicks;
    const historyNext=history.size+1,clockLag=historyNext-boundary,rowsAtNext=(rawPicks||[]).filter(pick=>Number(pick.pickNo)===historyNext),nextPickCompleted=(clockLag===0||clockLag===1)&&rowsAtNext.length>0&&new Set(rowsAtNext.map(pick=>`${clean(pick.playerId)}:${Number(pick.slot)||0}`)).size===1,effectiveBoundary=nextPickCompleted?historyNext+1:boundary;
    // ESPN can append an Auto-team result before repainting "On the Clock".
    // Accept only the single next, unambiguous history row, including one
    // immediate following Auto-team pick. Later-numbered virtualized rows remain
    // excluded and a clock rewind of more than one pick still truncates.
    for(const pickNo of [...history.keys()])if(Number(pickNo)>=effectiveBoundary)history.delete(pickNo);
    for(const pickNo of [...conflicts.keys()])if(Number(pickNo)>=effectiveBoundary)conflicts.delete(pickNo);
    return(rawPicks||[]).filter(pick=>Number(pick.pickNo)<effectiveBoundary)
  };
  const mergePickHistory=(history,rawPicks,teams,conflicts=new Map(),now=Date.now())=>{
    const grouped=new Map();
    for(const raw of rawPicks){
      const pickNo=Number(raw.pickNo),playerId=clean(raw.playerId);
      if(!Number.isInteger(pickNo)||pickNo<1||!playerId)continue;
      const pick={pickNo,playerId,slot:Number(raw.slot)||snakeSlot(pickNo,teams),name:clean(raw.name)},rows=grouped.get(pickNo)||new Map();
      rows.set(`${pick.playerId}:${pick.slot}`,pick);grouped.set(pickNo,rows)
    }
    for(const [pickNo,rows] of [...grouped.entries()].sort((a,b)=>a[0]-b[0])){
      const candidates=[...rows.values()],prior=history.get(pickNo),matchingPrior=prior&&candidates.find(pick=>pick.playerId===prior.playerId&&pick.slot===prior.slot);
      if(matchingPrior){conflicts.delete(pickNo);continue}
      if(!prior){
        if(candidates.length===1){history.set(pickNo,candidates[0]);conflicts.delete(pickNo)}
        continue
      }
      if(candidates.length!==1)continue;
      const candidate=candidates[0],signature=`${candidate.playerId}:${candidate.slot}`,pending=conflicts.get(pickNo),next=pending?.signature===signature?{...pending,count:pending.count+1,lastSeen:now}:{signature,count:1,firstSeen:now,lastSeen:now,candidate};
      conflicts.set(pickNo,next);
      // ESPN virtualizes and reuses pick-history rows during fast Auto-team runs.
      // Keep the previously verified pick unless a clean replacement persists long
      // enough to represent a real commissioner undo/correction.
      if(next.count<8||now-next.firstSeen<1500)continue;
      for(const knownPick of [...history.keys()])if(knownPick>=pickNo)history.delete(knownPick);
      history.set(pickNo,candidate);conflicts.delete(pickNo)
    }
    return normalizePicks([...history.values()],teams)
  };
  // ESPN uses 999 and larger values as an unranked-player sentinel. They are
  // not draft market data and must never become a fake ADP.
  const usableMarketRank=value=>{const rank=Number(value);return Number.isFinite(rank)&&rank>0&&rank<500?rank:null};
  const NFL_TEAM_CODES=new Set(["ARI","ATL","BAL","BUF","CAR","CHI","CIN","CLE","DAL","DEN","DET","GB","HOU","IND","JAX","KC","LV","LAC","LAR","MIA","MIN","NE","NO","NYG","NYJ","PHI","PIT","SEA","SF","TB","TEN","WAS"]);
  const nflTeamFromText=value=>clean(value).toUpperCase().split(/[^A-Z]+/).find(token=>NFL_TEAM_CODES.has(token))||"";
  const mergePlayer=(prior,next)=>{const nextRank=usableMarketRank(next.adp),priorRank=usableMarketRank(prior?.adp),hasNextRank=nextRank!==null,hasPriorRank=priorRank!==null,nextName=usablePlayerName(next.name),priorName=usablePlayerName(prior?.name);return{...prior,...next,name:nextName||priorName,position:next.position&&next.position!=="NA"?next.position:prior?.position||"NA",team:next.team||prior?.team||"",platformProjection:Number(next.platformProjection)>0?Number(next.platformProjection):Number(prior?.platformProjection||0),adp:hasNextRank?nextRank:hasPriorRank?priorRank:null,adpSource:hasNextRank?next.adpSource||"espn-rank":hasPriorRank?prior.adpSource||"espn-rank":"unavailable",adpSd:hasNextRank?next.adpSd??null:hasPriorRank?prior.adpSd??null:null,adpSdSource:hasNextRank?next.adpSdSource||"rank-calibrated":hasPriorRank?prior.adpSdSource||"rank-calibrated":"rank-calibrated",eligibleForRecommendation:Number(next.platformProjection)>0||prior?.eligibleForRecommendation===true}};
  const espnFeedPlayers=(payload,season,reception=1)=>{
    const positions={1:"QB",2:"RB",3:"WR",4:"TE",5:"K",16:"DST"},result=[];
    for(const entry of Array.isArray(payload?.players)?payload.players:[]){
      const player=entry?.player||entry,position=positions[Number(player?.defaultPositionId)];
      if(!position)continue;
      const projectedStats=[...(Array.isArray(player?.stats)?player.stats:[]),...(Array.isArray(entry?.stats)?entry.stats:[])].filter(stat=>String(stat?.externalId??stat?.seasonId)===String(season)&&Number(stat?.statSourceId)===1&&Number(stat?.statSplitTypeId)===0),projected=projectedStats.find(stat=>Number(stat?.appliedTotal||stat?.appliedTotalAdjusted)>0)||projectedStats[0],rankGroups=entry?.draftRanksByRankType||player?.draftRanksByRankType||{},preferredRankType=Number(reception)>=.75?"PPR":Number(reception)>=.25?"HALF":"STANDARD",rank=[preferredRankType,...["PPR","HALF","STANDARD"].filter(key=>key!==preferredRankType)].map(key=>Number(rankGroups?.[key]?.rank)).find(value=>Number.isFinite(value)&&value>0)||Number(entry?.draftRank||entry?.rank)||0,id=clean(player?.id||entry?.id),name=clean(player?.fullName||player?.name||entry?.fullName||entry?.name),platformProjection=Number(projected?.appliedTotal||projected?.appliedTotalAdjusted||0);
      if(!id||!name)continue;
      const marketRank=usableMarketRank(rank);
      result.push({id,name,position,team:clean(player?.proTeamAbbrev||entry?.proTeamAbbrev),platformProjection,projectionSeason:Number(season),adp:marketRank,adpSource:marketRank!==null?"espn-rank":"unavailable",adpSd:null,adpSdSource:"rank-calibrated",adpSeason:Number(season),adpProvider:"espn",adpFetchedAt:Date.now(),eligibleForRecommendation:platformProjection>0});
    }
    return result;
  };
  const mountedProjectionCoverage=(players,picks,minCount=5)=>{const drafted=new Set((picks||[]).map(pick=>clean(pick.playerId))),supported=new Set(["QB","RB","WR","TE","K","DST","D/ST"]),projected=[...(players||[])].filter(player=>!drafted.has(clean(player.id))&&supported.has(clean(player.position).toUpperCase())&&Number(player.platformProjection)>0).sort((a,b)=>clean(a.id).localeCompare(clean(b.id)));return{count:projected.length,ready:projected.length>=minCount,signature:JSON.stringify(projected.map(player=>[clean(player.id),Number(player.platformProjection),Number(player.adp)||0]))}};
  const deriveLeagueSettings=({teamCount,rosterRows,limitText,scoringText})=>{const labels=(rosterRows||[]).map(text=>clean(text).match(/^(QB|RB|WR|TE|FLEX|D\/ST|K|BE|BN)/i)?.[1]?.toUpperCase()).filter(Boolean),limit=clean(limitText).match(/^\d+\/(\d+) Players$/i),rounds=Number(limit?.[1]||labels.length),knownScoring=/\b(?:standard|non[-\s]?ppr|ppr)\b|\b0\.5\s*ppr\b|\b(?:half[-\s]?point(?:s)?|point(?:s)?) per reception\b|\bhead to head points\b/i.test(clean(scoringText));if(!Number.isInteger(teamCount)||teamCount<4||!Number.isInteger(rounds)||rounds<1||labels.length!==rounds||!knownScoring)return null;const count=label=>labels.filter(value=>value===label).length,slots={QB:count("QB"),RB:count("RB"),WR:count("WR"),TE:count("TE"),FLEX:count("FLEX"),K:count("K"),DST:count("D/ST"),BENCH:count("BE")+count("BN")},starters=slots.QB+slots.RB+slots.WR+slots.TE+slots.FLEX+slots.K+slots.DST;if(starters<1||starters+slots.BENCH!==rounds)return null;return{teams:teamCount,rounds,slots,scoring:{reception:receptionValue(scoringText)},playoffTeams:Math.min(6,teamCount)}};
  const deriveLeagueSettingsFromApi=(payload,teamCount)=>{const settings=payload?.settings||payload?.content?.settings||{},rosterSettings=settings?.rosterSettings||{},counts=rosterSettings.lineupSlotCounts||{},slot=id=>Math.max(0,Number(counts[id]??counts[String(id)]??0)||0),slots={QB:slot(0),RB:slot(2),WR:slot(4),TE:slot(6),FLEX:slot(23),K:slot(17),DST:slot(16),BENCH:slot(20)},rawLimits=rosterSettings.positionLimits||{},positionIds={QB:1,RB:2,WR:3,TE:4,K:5,DST:16},positionLimits=Object.fromEntries(Object.entries(positionIds).flatMap(([position,id])=>{const value=Number(rawLimits[id]??rawLimits[String(id)]);return Number.isFinite(value)&&value>=0?[[position,value]]:[]})),rounds=Object.values(slots).reduce((sum,value)=>sum+value,0),scoringItems=settings?.scoringSettings?.scoringItems,receptionItem=Array.isArray(scoringItems)?scoringItems.find(item=>Number(item?.statId)===53):null,reception=receptionItem?Number(receptionItem.points):0,playoffTeams=Number(settings?.scheduleSettings?.playoffTeamCount);if(!Number.isInteger(Number(teamCount))||Number(teamCount)<4||!Number.isInteger(rounds)||rounds<4||!Array.isArray(scoringItems)||!Number.isFinite(reception))return null;return{teams:Number(teamCount),rounds,slots,positionLimits,scoring:{reception},playoffTeams:Number.isInteger(playoffTeams)&&playoffTeams>=2?Math.min(playoffTeams,Number(teamCount)):Math.min(6,Number(teamCount))}};
  const helpers={contiguousTeamOrder,teamOrderFromSelects,slotForTeam,receptionValue,currentPickFromTexts,userSlotFromClockTexts,visibleOverallRank,pickNumberFromRow,normalizePicks,completedPicksBeforeClock,mergePickHistory,mergePlayer,espnFeedPlayers,nflTeamFromText,usablePlayerName,mountedProjectionCoverage,deriveLeagueSettings,deriveLeagueSettingsFromApi};
  if(globalThis.__draftChampionEspnTestMode){globalThis.__draftChampionEspnHelpers=helpers;return}

  const espnDraftId=(value=location.href)=>{const url=new URL(value,location.origin);return /\/football\/draft\/?$/i.test(url.pathname)&&url.searchParams.get("leagueId")?url.searchParams.get("leagueId"):null};
  function watchEspnNavigation(){if(globalThis.__draftChampionEspnNavigationWatch)return;const watcher={href:location.href};globalThis.__draftChampionEspnNavigationWatch=watcher;watcher.timer=setInterval(()=>{if(location.href===watcher.href)return;watcher.href=location.href;chrome.runtime.sendMessage({type:"ESPN_LOCATION_CHANGED",url:watcher.href}).catch(()=>{})},250)}
  watchEspnNavigation();
  if(!espnDraftId())return;
  const adapterVersion="2026-07-23b",params=new URL(location.href).searchParams,leagueId=espnDraftId(),projectionSeason=Number(params.get("seasonId")||new Date().getFullYear());if(!leagueId)return;const existingAdapter=globalThis.__draftChampionEspnAdapter;if(existingAdapter){clearInterval(existingAdapter.pollTimer);existingAdapter.stop?.();if(globalThis.__draftChampionEspnAdapter===existingAdapter)globalThis.__draftChampionEspnAdapter=null}const settingsCacheKey=`espnSettings:${projectionSeason}:${leagueId}`,catalogCacheKey=`espnCatalog:${projectionSeason}:${leagueId}`,sessionCache=await chrome.storage.session.get([settingsCacheKey,catalogCacheKey]).catch(()=>({})),cachedSettings=sessionCache[settingsCacheKey],cachedSettingsFresh=Date.now()-Number(cachedSettings?.at||0)<21600000,cachedScoringText=cachedSettingsFresh?clean(cachedSettings?.scoringText):"",cachedCatalog=sessionCache[catalogCacheKey],cachedCatalogFresh=Date.now()-Number(cachedCatalog?.at||0)<21600000&&Array.isArray(cachedCatalog?.players)&&cachedCatalog.players.length>=8,adapterSession={version:adapterVersion,leagueId,id:crypto.randomUUID(),updatedAt:Date.now(),phase:"connecting",lastError:"",catalog:new Map((cachedCatalogFresh?cachedCatalog.players:[]).map(player=>[clean(player.id),player]).filter(([id])=>id)),pickHistory:new Map(),pickConflicts:new Map(),lastFingerprint:"",lastPickFingerprint:"",lastHeartbeatAt:0,pendingRestartSignature:"",pendingRestartCount:0,pendingReadyPickCount:null,pendingReadyPickAt:0,pendingProjectionSignature:null,pendingProjectionAt:0,cachedScoringText,cachedLeagueSettings:cachedSettingsFresh?cachedSettings?.leagueSettings||null:null,verifiedUserSlot:null,settingsProbeStartedAt:0,restoreTabTitle:"",feedReady:cachedCatalogFresh,feedError:""};globalThis.__draftChampionEspnAdapter=adapterSession;const cacheLeagueSettings=leagueSettings=>{adapterSession.cachedLeagueSettings=leagueSettings;chrome.storage.session.set({[settingsCacheKey]:{scoringText:adapterSession.cachedScoringText,leagueSettings,at:Date.now()}}).catch(()=>{})},cacheCatalog=()=>chrome.storage.session.set({[catalogCacheKey]:{players:[...adapterSession.catalog.values()],at:Date.now()}}).catch(()=>{});const activation=await chrome.runtime.sendMessage({type:"ADAPTER_ACTIVATED",platform:"espn",draftId:leagueId,adapterSessionId:adapterSession.id});if(!activation?.ok)throw new Error(activation?.error||"ESPN adapter could not register with Draft Goblin.");
  chrome.runtime.sendMessage({type:"ESPN_FETCH_SETTINGS",seasonId:projectionSeason,leagueId}).then(response=>{if(globalThis.__draftChampionEspnAdapter!==adapterSession||!response?.ok)return;const order=teamOrder(),apiSettings=deriveLeagueSettingsFromApi(response.data,order.length||detectTeams(order));if(apiSettings){cacheLeagueSettings(apiSettings);scheduleUpdate()}}).catch(()=>{});
  chrome.runtime.sendMessage({type:"ESPN_FETCH_DRAFT_INIT",seasonId:projectionSeason,leagueId}).then(response=>{if(globalThis.__draftChampionEspnAdapter!==adapterSession)return;if(!response?.ok){adapterSession.feedError=response?.error||"ESPN player feed failed.";adapterSession.feedReady=true;scheduleUpdate();return}const order=teamOrder(),apiSettings=deriveLeagueSettingsFromApi(response.data,order.length||detectTeams(order));if(apiSettings)cacheLeagueSettings(apiSettings);const reception=Number(apiSettings?.scoring?.reception??adapterSession.cachedLeagueSettings?.scoring?.reception??receptionValue(adapterSession.cachedScoringText)),feedPlayers=espnFeedPlayers(response.data,projectionSeason,reception);for(const player of feedPlayers)adapterSession.catalog.set(player.id,mergePlayer(adapterSession.catalog.get(player.id)||{},player));adapterSession.feedReady=true;if(feedPlayers.length>=8)cacheCatalog();scheduleUpdate()}).catch(error=>{adapterSession.feedError=error?.message||"ESPN player feed failed.";adapterSession.feedReady=true;scheduleUpdate()});
  const extensionContextInvalid=error=>/extension context invalidated|receiving end does not exist|message port closed/i.test(String(error?.message||error||""));
  const sendAdapterHeartbeat=()=>{try{return chrome.runtime.sendMessage({type:"ADAPTER_HEARTBEAT",platform:"espn",draftId:leagueId,adapterSessionId:adapterSession.id,phase:adapterSession.phase,error:adapterSession.lastError}).then(response=>{if(response?.stale)stopAdapter()}).catch(error=>{if(extensionContextInvalid(error))stopAdapter()})}catch(error){if(extensionContextInvalid(error))stopAdapter();return Promise.resolve()}};
  const reportLoading=()=>{adapterSession.phase="connecting";adapterSession.lastError="";return sendAdapterHeartbeat()};
  const reportError=message=>{adapterSession.phase="error";adapterSession.lastError=message;return chrome.runtime.sendMessage({type:"DRAFT_ERROR",platform:"espn",adapterSessionId:adapterSession.id,error:message})};
  const playerName=root=>{for(const selector of [".player-name",".playerinfo__playername",'[class*="playerName"]','a[href*="/players/"],a[href*="/player/"]',"a"]){const nodes=root?.querySelectorAll?[...root.querySelectorAll(selector)]:[root?.querySelector?.(selector)].filter(Boolean);for(const node of nodes){const name=usablePlayerName(node?.textContent);if(name)return name}}return""};
  const playerId=root=>clean(root.getAttribute("data-player-id")||root.querySelector("[data-player-id]")?.getAttribute("data-player-id")||playerName(root));
  const columnNumber=(root,headerPattern)=>{const table=root.closest("table,[role=table],[role=grid]"),headers=table?[...table.querySelectorAll("thead th,[role=columnheader]")]:[],index=headers.findIndex(header=>headerPattern.test(clean(header.textContent))),cells=[...root.querySelectorAll("td,[role=gridcell]")],value=Number(clean(cells[index]?.textContent));return index>=0&&Number.isFinite(value)&&value>0?value:0};
  const projectedPoints=root=>{for(const selector of ['[data-stat="projected_points"]','[data-column="projected"]','[aria-label*="projected" i]']){const value=Number(clean(root.querySelector(selector)?.textContent));if(value>0)return value}return columnNumber(root,/^(PTS|FPTS|PROJ(?:ECTED)?(?: PTS)?)$/i)};
  const marketRank=root=>{for(const selector of ['[data-stat="rank"]','[data-column="rank"]','[aria-label="rank" i]']){const value=usableMarketRank(clean(root.querySelector(selector)?.textContent));if(value!==null)return value}const value=usableMarketRank(columnNumber(root,/^(RK|RANK|OVERALL(?: RANK)?)$/i));if(value!==null)return value;return usableMarketRank(visibleOverallRank(root.querySelector("td,[role=gridcell]")?.textContent,root.textContent))};
  function teamOrder(){return teamOrderFromSelects([...document.querySelectorAll("select")].map(select=>({testId:select.getAttribute("data-testid"),selectedValue:select.value,options:[...select.options].map(option=>({value:option.value,text:option.textContent}))})),Number(params.get("teamId")))}
  function currentPickNo(){const targeted=currentPickFromTexts([...document.querySelectorAll('[class*="on-the-clock" i], [data-testid*="on-the-clock" i]')].map(node=>node.textContent));if(targeted)return targeted;for(const root of [document.querySelector("header"),document.querySelector("main")]){if(!root)continue;const walker=document.createTreeWalker(root,1);for(let node=walker.currentNode;node;node=walker.nextNode()){if(node.childElementCount)continue;const pickNo=currentPickFromTexts([node.textContent]);if(pickNo)return pickNo}}const pageMatch=clean(document.body?.textContent).match(/on the clock:\s*pick\s*\d+(?!\d)/i);return currentPickFromTexts([pageMatch?.[0]])}
  function detectTeams(order){if(order.length)return order.length;const ids=[...new Set([...document.querySelectorAll("[data-team-id]")].map(el=>el.getAttribute("data-team-id")))],values=contiguousTeamOrder(ids);if(values.length)return values.length;const names=new Set([...document.querySelectorAll(".picklist--pick .pick-component[title]")].map(el=>el.getAttribute("title")).filter(Boolean)),boardColumns=document.querySelectorAll('[class*="draftColumn"], [class*="DraftBoard__team"]');return names.size>=4?names.size:boardColumns.length>=4?boardColumns.length:0}
  function scoringEvidence(){const mainText=clean(document.querySelector("main")?.innerText),rulesText=/\bScoring Type\b/i.test(mainText)?mainText.match(/\bHead to Head Points(?:\s*,\s*(?:Half[-\s]?Point(?:s)? Per Reception|Point(?:s)? Per Reception))?|\b(?:Standard|Non[-\s]?PPR|Half[-\s]?PPR|0\.5\s*PPR|PPR)\b/i)?.[0]||"":"";return[adapterSession.cachedScoringText,clean(document.querySelector("h1")?.textContent),...[...document.querySelectorAll('[data-testid*="scoring" i], [class*="scoring" i]')].map(el=>clean(el.textContent)),rulesText].filter(Boolean).join(" ")}
  function settings(teamCount){if(adapterSession.cachedLeagueSettings?.teams===teamCount)return adapterSession.cachedLeagueSettings;const rosterRows=[...document.querySelectorAll("table tr")].map(row=>clean(row.textContent)).filter(text=>/^(QB|RB|WR|TE|FLEX|D\/ST|K|BE|BN)\s*(?:Empty|\S)/i.test(text)),limit=[...document.querySelectorAll("main *")].map(el=>clean(el.textContent)).find(text=>/^\d+\/\d+ Players$/i.test(text)),scoringText=scoringEvidence(),leagueSettings=deriveLeagueSettings({teamCount,rosterRows,limitText:limit,scoringText});if(leagueSettings){adapterSession.cachedScoringText=scoringText||adapterSession.cachedScoringText;cacheLeagueSettings(leagueSettings)}return leagueSettings||adapterSession.cachedLeagueSettings}
  function update(){
    const order=teamOrder(),teamCount=detectTeams(order),leagueSettings=settings(teamCount),rows=[...document.querySelectorAll('[data-testid*="pick"], [data-pick], [data-pick-number], .draft-pick, .pick-history-item, .pick-history [role="row"], table tr')].filter(row=>row.querySelector('[data-player-id], .playerinfo__playername, [class*="playerName"]')&&pickNumberFromRow(row)>0);
    if(teamCount<4)return reportLoading();
    // League settings are verified without changing the draft view.
    if(!leagueSettings)return reportLoading()
    const detectedCurrentPick=currentPickNo(),observedPicks=rows.map(row=>{const pickNo=pickNumberFromRow(row),id=playerId(row),explicitSlot=Number(row.getAttribute("data-slot")||row.getAttribute("data-draft-slot"));return{pickNo,playerId:id,slot:explicitSlot||snakeSlot(pickNo,teamCount),name:playerName(row)}}),rawPicks=completedPicksBeforeClock(observedPicks,detectedCurrentPick,adapterSession.pickHistory,adapterSession.pickConflicts),expectedPicks=teamCount*leagueSettings.rounds,rawNormalized=normalizePicks(rawPicks,teamCount);if(adapterSession.pickHistory.size>=expectedPicks&&!rawNormalized.error&&rawNormalized.picks.length<adapterSession.pickHistory.size){const signature=JSON.stringify(rawNormalized.picks.map(pick=>[pick.pickNo,pick.playerId,pick.slot]));if(signature===adapterSession.pendingRestartSignature)adapterSession.pendingRestartCount++;else{adapterSession.pendingRestartSignature=signature;adapterSession.pendingRestartCount=1}if(adapterSession.pendingRestartCount>=2){adapterSession.pickHistory.clear();adapterSession.pickConflicts.clear();adapterSession.lastFingerprint="";adapterSession.pendingRestartSignature="";adapterSession.pendingRestartCount=0}}else{adapterSession.pendingRestartSignature="";adapterSession.pendingRestartCount=0}const normalized=mergePickHistory(adapterSession.pickHistory,rawPicks,teamCount,adapterSession.pickConflicts);
    if(normalized.error)return reportLoading();const picks=normalized.picks;
    const pickFingerprint=JSON.stringify(picks.map(pick=>[pick.pickNo,pick.playerId,pick.slot]));if(pickFingerprint!==adapterSession.lastPickFingerprint){adapterSession.lastPickFingerprint=pickFingerprint;chrome.runtime.sendMessage({type:"DRAFT_PICK_UPDATE",platform:"espn",draftId:leagueId,adapterSessionId:adapterSession.id,currentPickNo:detectedCurrentPick,picks}).catch(()=>{})}
    const candidates=[...document.querySelectorAll('[data-player-id], .playerinfo__playername, [class*="playerName"]'),...rows],currentCatalog=new Map();
    for(const node of candidates){const root=node.closest('[role="row"], tr, li')||node.closest("[data-player-id], [class*=player]")||node,id=playerId(root),name=playerName(root)||usablePlayerName(node.textContent);if(!id||!name)continue;const descriptor=clean(root.textContent),position=clean(root.querySelector(".positionPill")?.textContent)||(descriptor.match(/\b(QB|RB|WR|TE|DST|D\/ST|K)\b/)||[,"NA"])[1],team=clean(root.querySelector(".playerinfo__playerteam")?.textContent)||nflTeamFromText(descriptor),platformProjection=projectedPoints(root),adp=marketRank(root),player={id,name,position:position.replace("D/ST","DST"),team,platformProjection,projectionSeason,adp:adp||null,adpSource:adp?"espn-rank":"unavailable",adpSd:null,adpSdSource:"rank-calibrated",adpSeason:projectionSeason,adpProvider:"espn",adpFetchedAt:Date.now(),eligibleForRecommendation:platformProjection>0};currentCatalog.set(id,mergePlayer(currentCatalog.get(id)||{},player))}
    for(const [id,player] of currentCatalog)adapterSession.catalog.set(id,mergePlayer(adapterSession.catalog.get(id)||{},player));for(const pick of picks)if(!adapterSession.catalog.has(pick.playerId))adapterSession.catalog.set(pick.playerId,{id:pick.playerId,name:pick.name||pick.playerId,position:"NA",team:"",eligibleForRecommendation:false});
    const players=[...adapterSession.catalog.values()];if(!adapterSession.feedReady&&players.length<8)return;if(players.length<8||picks.some(p=>!adapterSession.catalog.has(p.playerId)))return reportError("ESPN player catalog could not be reconciled with draft picks; recommendations disabled.");
    const teamId=Number(params.get("teamId")),selectUserSlot=slotForTeam(order,teamId),clockUserSlot=userSlotFromClockTexts([document.body?.textContent],detectedCurrentPick,teamCount);if(Number.isInteger(clockUserSlot)&&clockUserSlot>=1)adapterSession.verifiedUserSlot=clockUserSlot;const userSlot=adapterSession.verifiedUserSlot||selectUserSlot;if(!Number.isInteger(userSlot)||userSlot<1)return reportLoading();
    const adpScoring=leagueSettings.scoring.reception>=.75?"ppr":leagueSettings.scoring.reception>=.25?"half-ppr":"standard";for(const player of players){player.adpTeams=teamCount;player.adpScoring=adpScoring}const historyCurrentPick=picks.length+1,historyCaughtUp=!detectedCurrentPick||detectedCurrentPick<=historyCurrentPick,now=Date.now(),projectionCoverage=mountedProjectionCoverage(currentCatalog.values(),picks);if(historyCaughtUp){if(adapterSession.pendingReadyPickCount!==picks.length){adapterSession.pendingReadyPickCount=picks.length;adapterSession.pendingReadyPickAt=now;adapterSession.pendingProjectionSignature=null;adapterSession.pendingProjectionAt=0;return}if(adapterSession.pendingProjectionSignature!==projectionCoverage.signature){adapterSession.pendingProjectionSignature=projectionCoverage.signature;adapterSession.pendingProjectionAt=now;return}const projectionsStable=now-adapterSession.pendingProjectionAt>=500,projectionWaitExpired=now-adapterSession.pendingReadyPickAt>=2500;if(!projectionsStable||!projectionCoverage.ready&&!projectionWaitExpired)return}else{adapterSession.pendingReadyPickCount=null;adapterSession.pendingReadyPickAt=0;adapterSession.pendingProjectionSignature=null;adapterSession.pendingProjectionAt=0}adapterSession.phase="live";adapterSession.lastError="";const draftStatus=picks.length>=expectedPicks?"complete":detectedCurrentPick||picks.length?"drafting":"predraft",fingerprint=JSON.stringify([userSlot,detectedCurrentPick,draftStatus,leagueSettings,picks.map(pick=>[pick.pickNo,pick.playerId,pick.slot]),players.map(player=>[player.id,player.position,player.team,player.platformProjection,player.adp,player.eligibleForRecommendation])]);if(fingerprint===adapterSession.lastFingerprint){if(Date.now()-adapterSession.lastHeartbeatAt>=1000){adapterSession.lastHeartbeatAt=Date.now();chrome.runtime.sendMessage({type:"DRAFT_HEARTBEAT",platform:"espn",draftId:leagueId,adapterSessionId:adapterSession.id,updatedAt:adapterSession.lastHeartbeatAt}).then(response=>{if(response?.ok)adapterSession.updatedAt=Date.now()})}return}adapterSession.lastFingerprint=fingerprint;chrome.runtime.sendMessage({type:"DRAFT_STATE",adapterSessionId:adapterSession.id,state:{platform:"espn",draftId:leagueId,draftStatus,projectionSeason,userSlot,currentPickNo:detectedCurrentPick,settings:leagueSettings,picks,players,updatedAt:Date.now()}}).then(()=>{adapterSession.updatedAt=Date.now()})
  }
  let timer,updateInFlight=false,updateQueued=false,navigated=false,lastUpdateAt=0;
  const semanticSelector='select, table, [data-team-id], [data-player-id], [data-testid*="pick"], [data-pick], [data-pick-number], .draft-pick, .pick-history-item, .pick-history, [class*="playerName"], [class*="scoring"]';
  const semanticMutation=records=>records.some(record=>{const target=record.target?.nodeType===1?record.target:record.target?.parentElement;if(target?.closest?.(semanticSelector))return true;return[...record.addedNodes].some(node=>node.nodeType===1&&(node.matches?.(semanticSelector)||node.querySelector?.(semanticSelector)))});
  const observer=new MutationObserver(records=>{if(semanticMutation(records))scheduleUpdate()});
  const stopAdapter=()=>{if(navigated)return;navigated=true;if(timer!=null)clearTimeout(timer);clearInterval(adapterSession.pollTimer);clearInterval(adapterSession.healthTimer);observer.disconnect();if(globalThis.__draftChampionEspnAdapter===adapterSession)globalThis.__draftChampionEspnAdapter=null};
  const runUpdate=()=>{timer=null;if(navigated||document.hidden)return;if(!chrome.runtime?.id){stopAdapter();return}if(updateInFlight){updateQueued=true;return}updateInFlight=true;lastUpdateAt=Date.now();try{update()}finally{updateInFlight=false;if(updateQueued){updateQueued=false;scheduleUpdate()}}};
  const scheduleUpdate=()=>{if(navigated||document.hidden||timer!=null)return;const delay=Math.max(40,100-(Date.now()-lastUpdateAt));timer=setTimeout(runUpdate,delay)};
  const stopForNavigation=()=>{if(navigated)return;const runtimeAvailable=Boolean(chrome.runtime?.id);stopAdapter();if(runtimeAvailable)chrome.runtime.sendMessage({type:"DRAFT_NAVIGATED",adapterSessionId:adapterSession.id}).catch(()=>{})};
  adapterSession.stop=stopAdapter;
  observer.observe(document.documentElement,{childList:true,characterData:true,subtree:true});sendAdapterHeartbeat();adapterSession.healthTimer=setInterval(sendAdapterHeartbeat,1000);update();adapterSession.pollTimer=setInterval(()=>{if(globalThis.__draftChampionEspnAdapter!==adapterSession){stopAdapter();return}if(!chrome.runtime?.id){stopAdapter();return}if(espnDraftId()!==leagueId){stopForNavigation();return}if(document.hidden)return;runUpdate()},250);document.addEventListener("visibilitychange",()=>{if(!document.hidden&&globalThis.__draftChampionEspnAdapter===adapterSession){if(espnDraftId()!==leagueId)stopForNavigation();else runUpdate()}});
})().catch(error=>{try{const url=new URL(location.href),draftId=url.searchParams.get("leagueId")||"";chrome.runtime.sendMessage({type:"ADAPTER_BOOT_ERROR",platform:"espn",draftId,error:error?.message||"ESPN adapter failed during startup."}).catch(()=>{})}catch{}});
