(()=>{
function sleeperDraftId(value=location.href){const url=new URL(value,location.origin),queryId=url.searchParams.get("draft_id"),pathIds=[...url.pathname.matchAll(/(?:^|\/)([0-9]{10,})(?=\/|$)/g)].map(match=>match[1]);return /^\d{10,}$/.test(String(queryId||""))?String(queryId):pathIds.at(-1)||null}
function sleeperSlot(settings,key){const value=Number(settings?.[key]);return Number.isFinite(value)&&value>=0?value:0}
function sleeperLeagueSettings(draft,reception){const settings=draft?.settings||{},teams=sleeperSlot(settings,"teams"),rounds=sleeperSlot(settings,"rounds"),slots={QB:sleeperSlot(settings,"slots_qb"),RB:sleeperSlot(settings,"slots_rb"),WR:sleeperSlot(settings,"slots_wr"),TE:sleeperSlot(settings,"slots_te"),FLEX:sleeperSlot(settings,"slots_flex"),K:sleeperSlot(settings,"slots_k"),DST:sleeperSlot(settings,"slots_def")},starters=Object.values(slots).reduce((sum,count)=>sum+count,0),explicitBench=Number(settings.slots_bn);slots.BENCH=Number.isFinite(explicitBench)&&explicitBench>=0?explicitBench:Math.max(0,rounds-starters);const defaults={QB:slots.QB+1,RB:slots.RB+slots.FLEX+Math.max(1,Math.ceil(slots.BENCH*.35)),WR:slots.WR+slots.FLEX+Math.max(1,Math.ceil(slots.BENCH*.35)),TE:slots.TE+1,K:slots.K,DST:slots.DST},limitKeys={QB:"max_qb",RB:"max_rb",WR:"max_wr",TE:"max_te",K:"max_k",DST:"max_def"},positionLimits=Object.fromEntries(Object.entries(defaults).map(([position,fallback])=>{const key=limitKeys[position],configured=Number(settings[key]);return[position,Object.hasOwn(settings,key)&&Number.isFinite(configured)&&configured>=0?Math.min(fallback,configured):fallback]}));return{teams,rounds,scoring:{reception},slots,positionLimits,playoffTeams:Math.min(6,teams)}}
function assertSupportedSleeperDraft(draft){const settings=draft?.settings||{},type=String(draft?.type||"").toLowerCase(),reversalRound=sleeperSlot(settings,"reversal_round"),superFlex=Math.max(sleeperSlot(settings,"slots_super_flex"),sleeperSlot(settings,"slots_superflex"),sleeperSlot(settings,"slots_op"));if(type!=="snake")throw new Error("Draft Goblin currently supports Sleeper snake drafts only.");if(reversalRound>0)throw new Error("Sleeper third-round-reversal drafts are not supported yet.");if(superFlex>0)throw new Error("Sleeper superflex drafts are not supported yet.")}
const clean=value=>String(value||"").trim(),normalizedName=value=>clean(value).toLowerCase().replace(/[^a-z0-9]/g,"");
let visibleCatalogCache,visibleCatalogIndexes;
function visibleSleeperSignals(catalog){
  if(visibleCatalogCache!==catalog){const byId=new Map(Object.values(catalog).map(player=>[String(player.player_id),player])),byName=new Map();for(const player of byId.values()){const key=normalizedName(player.full_name||`${player.first_name||""} ${player.last_name||""}`);if(!key)continue;const current=byName.get(key);byName.set(key,current===undefined?player:null)}visibleCatalogCache=catalog;visibleCatalogIndexes={byId,byName}}
  const{byId,byName}=visibleCatalogIndexes;
  const result=new Map(),roots=[...new Set(document.querySelectorAll('[data-player-id],[data-player_id],[role="row"],tr,.player-rank-item2'))],visible=element=>element?.hidden!==true&&element?.getAttribute?.("aria-hidden")!=="true"&&(typeof element?.getClientRects!=="function"||element.getClientRects().length>0),numberFor=(root,pattern)=>{for(const element of root.querySelectorAll?.('[aria-label],[title],[data-stat],[data-column],[data-testid],[class]')||[]){const descriptor=[element.getAttribute?.("aria-label"),element.getAttribute?.("title"),element.getAttribute?.("data-stat"),element.getAttribute?.("data-column"),element.getAttribute?.("data-testid"),element.className].map(clean).join(" ").replace(/[-_]+/g," ");if(!pattern.test(descriptor))continue;const matches=clean(element.textContent).replace(/,/g,"").match(/-?\d+(?:\.\d+)?/g)||[];if(matches.length!==1)continue;const value=Number(matches[0]);if(value>0)return value}return 0},adpFromRowText=(root,player)=>{const name=clean(player?.full_name||`${player?.first_name||""} ${player?.last_name||""}`),position=clean(player?.position),team=clean(player?.team),text=clean(root?.innerText||root?.textContent).replace(/\s+/g," ");if(!name||!position||!text)return 0;const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),suffix=team?`\\s+${team}`:"";const match=text.match(new RegExp(`${escaped}\\s+${position}${suffix}\\s+(\\d+(?:\\.\\d+)?)\\b`,"i"));return match&&Number(match[1])>0?Number(match[1]):0};
  for(const root of roots){
    if(!visible(root))continue;
    const id=clean(root.getAttribute?.("data-player-id")||root.getAttribute?.("data-player_id")||root.querySelector?.("[data-player-id],[data-player_id]")?.getAttribute?.("data-player-id")||root.querySelector?.("[data-player_id]")?.getAttribute?.("data-player_id"));
    let player=byId.get(id);
    if(!player){const nameRoot=root.querySelector?.(".name-wrapper,[class*='player-name'],[class*='player_name']"),directName=[...(nameRoot?.childNodes||[])].filter(node=>node.nodeType===3).map(node=>clean(node.textContent)).filter(Boolean).join(" ");player=byName.get(normalizedName(directName))}
    if(!player)for(const leaf of root.querySelectorAll?.("span,div")||[]){if(leaf.children?.length)continue;const candidate=byName.get(normalizedName(leaf.textContent));if(candidate){player=candidate;break}}
    if(!player)continue;
    const projection=numberFor(root,/(?:^|\s)(?:proj(?:ected)?|fpts|pts)(?:\s|$)/i),adp=numberFor(root,/(?:^|\s)adp(?:\s|$)/i)||adpFromRowText(root,player);
    if(projection>0||adp>0){const previous=result.get(String(player.player_id))||{};result.set(String(player.player_id),{projection:projection||previous.projection||0,adp:adp||previous.adp||0})}
  }
  return result;
}
(async function sleeperAdapter() {
  const draftId=sleeperDraftId();if(!draftId)return;
  const adapterVersion="2026-08-01a",existingAdapter=globalThis.__draftChampionSleeperAdapter;existingAdapter?.stop?.();if(globalThis.__draftChampionSleeperAdapter===existingAdapter)globalThis.__draftChampionSleeperAdapter=null;const adapterSession={version:adapterVersion,draftId,id:crypto.randomUUID(),updatedAt:Date.now(),phase:"connecting",lastError:""};globalThis.__draftChampionSleeperAdapter=adapterSession;const activation=await chrome.runtime.sendMessage({type:"ADAPTER_ACTIVATED",platform:"sleeper",draftId,adapterSessionId:adapterSession.id});if(!activation?.ok)throw new Error(activation?.error||"Sleeper adapter could not register with Draft Goblin.");
  const extensionContextInvalid=error=>/extension context invalidated|receiving end does not exist|message port closed/i.test(String(error?.message||error||""));
  const sendAdapterHeartbeat=()=>{try{return chrome.runtime.sendMessage({type:"ADAPTER_HEARTBEAT",platform:"sleeper",draftId,adapterSessionId:adapterSession.id,phase:adapterSession.phase,error:adapterSession.lastError}).then(response=>{if(response?.stale)stopAdapter()}).catch(error=>{if(extensionContextInvalid(error))stopAdapter()})}catch(error){if(extensionContextInvalid(error))stopAdapter();return Promise.resolve()}};
  let catalogCache,basePlayersCache,detectedUserId,detectedUserSlot,visibleSignalsCache=new Map(),draftCache,playersCache,slotDetectionKey="",slotDetectionPromise;
  const projectionSignalsCache=new Map(),projectionSignalsRequests=new Map(),marketCacheRequests=new Map(),PROJECTION_SIGNALS_TTL_MS=5*60*1000,MARKET_CACHE_MAX_AGE_MS=24*60*60*1000;
  async function liveJson(path) {
    const separator = path.includes("?") ? "&" : "?";
    const response = await chrome.runtime.sendMessage({ type: "SLEEPER_FETCH", url: `${path}${separator}_draftChampion=${Date.now()}` });
    if (!response?.ok) throw new Error(response?.error || "Sleeper live draft request failed.");
    return response.data;
  }
  async function playerCatalog() {
    // Sleeper's catalog is larger than Chrome's local-storage allowance.
    catalogCache ??= liveJson("https://api.sleeper.app/v1/players/nfl");
    return catalogCache;
  }
  async function fullDraftSignals(season,reception){
    const pointsKey=reception>=.75?"pts_ppr":reception>=.25?"pts_half_ppr":"pts_std",adpKey=reception>=.75?"adp_ppr":reception>=.25?"adp_half_ppr":"adp_std";
    const key=`${season}:${pointsKey}:${adpKey}`,cached=projectionSignalsCache.get(key),now=Date.now();if(cached&&now-cached.fetchedAt<PROJECTION_SIGNALS_TTL_MS)return cached.signals;if(projectionSignalsRequests.has(key))return projectionSignalsRequests.get(key);
    const storageKey=`sleeperMarketRank:${season}:${adpKey}`,loadMarketCache=()=>{if(marketCacheRequests.has(storageKey))return marketCacheRequests.get(storageKey);const request=(chrome.storage?.local?.get?chrome.storage.local.get(storageKey):Promise.resolve({})).then(stored=>{const entries=stored?.[storageKey]?.entries||{},valid=new Map();for(const[id,row]of Object.entries(entries)){const adp=Number(row?.adp),fetchedAt=Number(row?.fetchedAt);if(Number.isFinite(adp)&&adp>0&&adp<999&&Number.isFinite(fetchedAt)&&now-fetchedAt<=MARKET_CACHE_MAX_AGE_MS)valid.set(String(id),{adp,fetchedAt})}return valid}).catch(()=>new Map());marketCacheRequests.set(storageKey,request);return request},fetchRows=async()=>{let lastError;for(let attempt=0;attempt<2;attempt++){try{return await liveJson(`https://api.sleeper.com/projections/nfl/${season}?season_type=regular`)}catch(error){lastError=error;if(attempt===0)await new Promise(resolve=>setTimeout(resolve,100))}}throw lastError};
    const request=(async()=>{const persisted=await loadMarketCache();let rows;try{rows=await fetchRows();if(!Array.isArray(rows))throw new Error("Sleeper projection pool returned an invalid snapshot.")}catch{return cached?.signals||new Map([...persisted].map(([id,row])=>[id,{projection:0,adp:row.adp,adpFetchedAt:row.fetchedAt,cachedMarket:true}]))}const fetchedAt=Date.now(),signals=new Map(),nextEntries=Object.fromEntries([...persisted].map(([id,row])=>[id,row]));for(const row of rows){if(Number(row?.season)!==Number(season))continue;const id=clean(row?.player_id),projection=Number(row?.stats?.[pointsKey]),adp=Number(row?.stats?.[adpKey]);if(!id)continue;const liveAdp=Number.isFinite(adp)&&adp>0&&adp<999?adp:0,prior=persisted.get(id),marketAdp=liveAdp||Number(prior?.adp)||0;signals.set(id,{projection:Number.isFinite(projection)&&projection>0?projection:0,adp:marketAdp,adpFetchedAt:liveAdp?fetchedAt:Number(prior?.fetchedAt)||0,cachedMarket:!liveAdp&&marketAdp>0});if(liveAdp)nextEntries[id]={adp:liveAdp,fetchedAt}}projectionSignalsCache.set(key,{signals,fetchedAt});if(chrome.storage?.local?.set&&Object.keys(nextEntries).length)chrome.storage.local.set({[storageKey]:{schemaVersion:1,season:Number(season),scoring:adpKey,entries:nextEntries}}).catch(()=>{});return signals})().finally(()=>projectionSignalsRequests.delete(key));projectionSignalsRequests.set(key,request);return request;
  }
  async function playersFor(season,reception,teams) {
    const[catalog,fullSignals]=await Promise.all([playerCatalog(),fullDraftSignals(season,reception)]),visibleSignals=visibleSleeperSignals(catalog),fetchedAt=Date.now(),adpScoring=reception>=.75?"ppr":reception>=.25?"half-ppr":"standard";
    for(const[id,signal]of visibleSignals){const previous=visibleSignalsCache.get(id)||{};visibleSignalsCache.set(id,{projection:Number(signal.projection)||Number(previous.projection)||0,adp:Number(signal.adp)||Number(previous.adp)||0})}
    basePlayersCache??=Object.values(catalog).filter(p=>["QB","RB","WR","TE","K","DEF"].includes(p.position)).map(p=>({id:String(p.player_id),name:p.full_name||`${p.first_name||""} ${p.last_name||""}`.trim(),position:p.position==="DEF"?"DST":p.position,team:p.team,active:p.active!==false&&!["Inactive","Retired"].includes(String(p.status||"")),injuryStatus:p.injury_status||null,risk:p.injury_status?0.8:0.25,scarcity:["RB","TE"].includes(p.position)?0.65:0.4}));
    return basePlayersCache.map(player=>{const visible=visibleSignalsCache.get(player.id)||{},full=fullSignals.get(player.id)||{},platformProjection=Number(visible.projection)||Number(full.projection)||0,marketRank=Number(visible.adp)||Number(full.adp),marketRankAvailable=Number.isFinite(marketRank)&&marketRank>0&&marketRank<999,visibleProjection=Number(visible.projection)>0,visibleRank=Number(visible.adp)>0,cachedRank=!visibleRank&&Boolean(full.cachedMarket);return{...player,platformProjection,projectionSeason:Number(season),projectionSource:platformProjection>0?(visibleProjection?"Sleeper visible draft projection":"Sleeper private draft projection pool"):"unavailable",adp:marketRankAvailable?marketRank:null,adpSd:null,adpSdSource:"format-curve",adpSeason:Number(season),adpScoring,adpTeams:Number(teams),adpFetchedAt:visibleRank?fetchedAt:Number(full.adpFetchedAt)||fetchedAt,adpProvider:"sleeper",adpSource:marketRankAvailable?(visibleRank?"sleeper-visible-draft-rank":cachedRank?"sleeper-last-verified-draft-rank":"sleeper-private-draft-pool"):"unavailable"}});
  }
  async function detectedSlot(draft) {
    const order=draft.draft_order||{},knownIds=Object.keys(order),teams=Number(draft?.settings?.teams),validSlot=value=>{const slot=Number(value);return Number.isInteger(slot)&&slot>=1&&slot<=teams?slot:null};
    if(detectedUserId&&Object.hasOwn(order,detectedUserId)){const slot=validSlot(order[detectedUserId]);if(slot!==null)return slot}
    const preferred=[];
    for(let index=0;index<localStorage.length;index++){const key=String(localStorage.key(index)||""),value=String(localStorage.getItem(key)||"");if(!/user|auth|session|identity|account/i.test(key))continue;for(const id of knownIds)if(value===id||new RegExp(`(?:^|[^0-9])${id}(?:[^0-9]|$)`).test(value))preferred.push(id)}
    if(new Set(preferred).size===1){detectedUserId=preferred[0];return validSlot(order[detectedUserId])}
    const detectionKey=knownIds.slice().sort().join(":");if(slotDetectionKey!==detectionKey){slotDetectionKey=detectionKey;slotDetectionPromise=Promise.all(knownIds.map(async id=>{try{return{id,user:await liveJson(`https://api.sleeper.app/v1/user/${id}`)}}catch{return{id,user:null}}}))}
    const profiles=await(slotDetectionPromise||Promise.resolve([])),leafTexts=new Set([...document.querySelectorAll("body *")].filter(element=>!element.children.length).map(element=>String(element.textContent||"").trim().toLowerCase()).filter(Boolean)),visible=profiles.filter(({user})=>user?.username&&leafTexts.has(String(user.username).toLowerCase()));
    if(visible.length===1){detectedUserId=visible[0].id;return validSlot(order[detectedUserId])}
    return null;
  }
  function normalizedPicks(value,teams,rounds){
    if(!Array.isArray(value))throw new Error("Sleeper picks returned an invalid snapshot.");const byPick=new Map(),pickedPlayers=new Set(),maximum=teams*rounds;for(const row of value){const pickNo=Number(row?.pick_no),slot=Number(row?.draft_slot),playerId=clean(row?.player_id);if(!Number.isInteger(pickNo)||pickNo<1||pickNo>maximum||!Number.isInteger(slot)||slot<1||slot>teams||!playerId)throw new Error("Sleeper picks returned an invalid row.");if(byPick.has(pickNo))throw new Error("Sleeper picks returned duplicate pick numbers.");if(pickedPlayers.has(playerId))throw new Error("Sleeper picks returned a player more than once.");byPick.set(pickNo,{pickNo,playerId,slot});pickedPlayers.add(playerId)}const picks=[...byPick.values()].sort((a,b)=>a.pickNo-b.pickNo);if(picks.some((pick,index)=>pick.pickNo!==index+1))throw new Error("Sleeper picks returned a truncated sequence.");return picks
  }  async function update({pickOnly=false}={}) {
    try {
      const draft = pickOnly&&draftCache?draftCache:await liveJson(`https://api.sleeper.app/v1/draft/${draftId}`);if(String(draft?.draft_id||"")!==draftId)throw new Error("Sleeper returned a different draft than the open draftboard.");assertSupportedSleeperDraft(draft);draftCache=draft;const season=Number(draft.season||new Date().getFullYear());
      const reception=draft.metadata?.scoring_type==="ppr"?1:draft.metadata?.scoring_type==="half_ppr"?.5:0;
      const [picks,players]=await Promise.all([liveJson(`https://api.sleeper.app/v1/draft/${draftId}/picks`),pickOnly&&playersCache?Promise.resolve(playersCache):playersFor(season,reception,Number(draft.settings.teams))]);playersCache=players;
      const nextDetectedSlot=await detectedSlot(draft);if(nextDetectedSlot!==null)detectedUserSlot=nextDetectedSlot;
      const settings=sleeperLeagueSettings(draft,reception),normalized=normalizedPicks(picks,settings.teams,settings.rounds),draftStatus=normalized.length>=settings.teams*settings.rounds?"complete":String(draft.status||"");
      const state = { platform: "sleeper", draftId, draftRunId:`${draftId}:${Number(draft.created)||0}`, draftStatus, projectionSeason:season, userSlot: detectedUserSlot??null, settings, picks:normalized, players, updatedAt: Date.now() };
      if(globalThis.__draftChampionSleeperAdapter!==adapterSession||sleeperDraftId()!==draftId)return;adapterSession.phase="live";adapterSession.lastError="";await chrome.runtime.sendMessage({ type: "DRAFT_STATE", adapterSessionId:adapterSession.id, state });adapterSession.updatedAt=Date.now();
    } catch (error) { if(extensionContextInvalid(error)){stopAdapter();return}if(globalThis.__draftChampionSleeperAdapter===adapterSession){adapterSession.phase="error";adapterSession.lastError=error.message;try{chrome.runtime.sendMessage({ type: "DRAFT_ERROR", platform: "sleeper", adapterSessionId:adapterSession.id, error: error.message }).catch?.(()=>{})}catch{stopAdapter()}} }
  }
  let updateInFlight=false,queuedPickOnly=false,fastPickInFlight=false,fastPickQueued=false,pollTimer,mutationTimer,mutationObserver,stopped=false,lastImmediatePollAt=0;
  const stopAdapter=()=>{if(stopped)return;stopped=true;clearInterval(pollTimer);clearInterval(adapterSession.healthTimer);clearTimeout(mutationTimer);mutationObserver?.disconnect?.();if(globalThis.__draftChampionSleeperAdapter===adapterSession)globalThis.__draftChampionSleeperAdapter=null};adapterSession.stop=stopAdapter;
  async function poll({pickOnly=false}={}){if(stopped||globalThis.__draftChampionSleeperAdapter!==adapterSession){stopAdapter();return}if(sleeperDraftId()!==draftId){stopAdapter();chrome.runtime.sendMessage({type:"DRAFT_NAVIGATED",adapterSessionId:adapterSession.id});return}if(document.hidden)return;if(updateInFlight){queuedPickOnly=queuedPickOnly||pickOnly;return}updateInFlight=true;try{await update({pickOnly})}finally{updateInFlight=false;if(queuedPickOnly){queuedPickOnly=false;poll({pickOnly:true})}}}
  async function refreshPicksOnly(){if(stopped||document.hidden)return;if(fastPickInFlight){fastPickQueued=true;return}fastPickInFlight=true;try{const draft=draftCache||await liveJson(`https://api.sleeper.app/v1/draft/${draftId}`);if(String(draft?.draft_id||"")!==draftId)return;assertSupportedSleeperDraft(draft);draftCache=draft;const reception=draft.metadata?.scoring_type==="ppr"?1:draft.metadata?.scoring_type==="half_ppr"?.5:0,settings=sleeperLeagueSettings(draft,reception),raw=await liveJson(`https://api.sleeper.app/v1/draft/${draftId}/picks`),picks=normalizedPicks(raw,settings.teams,settings.rounds);await chrome.runtime.sendMessage({type:"DRAFT_PICK_UPDATE",platform:"sleeper",draftId,adapterSessionId:adapterSession.id,currentPickNo:picks.length+1,picks})}catch(error){if(extensionContextInvalid(error))stopAdapter()}finally{fastPickInFlight=false;if(fastPickQueued){fastPickQueued=false;refreshPicksOnly()}}}
  const scheduleImmediatePickRefresh=()=>{if(stopped||document.hidden||mutationTimer!=null)return;const delay=Math.max(20,120-(Date.now()-lastImmediatePollAt));mutationTimer=setTimeout(()=>{mutationTimer=null;lastImmediatePollAt=Date.now();refreshPicksOnly()},delay)};
  const initialHeartbeat=sendAdapterHeartbeat();adapterSession.healthTimer=setInterval(sendAdapterHeartbeat,1000);await initialHeartbeat;if(stopped||globalThis.__draftChampionSleeperAdapter!==adapterSession)return;if(typeof MutationObserver==="function"){const boardRoot=[...document.querySelectorAll('[class],[data-testid]')].find(element=>/draft.?board/i.test(`${element.className||""} ${element.getAttribute?.("data-testid")||""}`))||document.body;if(boardRoot){mutationObserver=new MutationObserver(records=>{if(records.some(record=>record.type==="characterData"||record.addedNodes?.length||record.removedNodes?.length))scheduleImmediatePickRefresh()});mutationObserver.observe(boardRoot,{subtree:true,childList:true,characterData:true})}}document.addEventListener("visibilitychange",()=>{if(!document.hidden)poll({pickOnly:true})});pollTimer=setInterval(poll,1000);await poll();if(stopped||globalThis.__draftChampionSleeperAdapter!==adapterSession)return;
})().catch(error=>{try{chrome.runtime.sendMessage({type:"ADAPTER_BOOT_ERROR",platform:"sleeper",draftId:sleeperDraftId()||"",error:error?.message||"Sleeper adapter failed during startup."}).catch(()=>{})}catch{}});
})();
